export const DEFAULT_STRATEGIC_MAP_SEED = 'historia-alpha-strategic-map-v1';
export const DEFAULT_STRATEGIC_MAP_WIDTH = 100;
export const DEFAULT_STRATEGIC_MAP_HEIGHT = 100;

export const DEFAULT_STRATEGIC_MAP_FACTIONS = Object.freeze([
  { id: 'aurora', label: 'Alliance d’Aurora', fill: '#2F6BFF', border: '#8FB3FF', homeColumn: 0 },
  { id: 'ember', label: 'Ligue d’Ember', fill: '#E8572A', border: '#FFB394', homeColumn: 2 },
  { id: 'neutral', label: 'Marches neutres', fill: '#64748B', border: '#CBD5E1', homeColumn: 1 },
]);

export const DEFAULT_STRATEGIC_MAP_PROVINCES = Object.freeze([
  {
    id: 'north-watch',
    name: 'Veille du Nord',
    grid: { col: 0, row: 0 },
    layout: { x: 15, y: 18, w: 20, h: 18 },
    labelLayout: { x: 26, y: 20, align: 'middle', tone: 'standard' },
    polygon: '8,24 24,12 39,10 47,18 46,36 34,42 18,40 8,32',
    ownerFactionId: 'aurora',
    controllingFactionId: 'aurora',
    supplyLevel: 'stable',
    loyalty: 84,
    strategicValue: 5,
    biome: 'continental',
    terrain: 'highland',
    altitudeMeters: 1200,
    latitude: 48,
    resourceIds: ['ore', 'timber'],
    tags: ['watch', 'mountain-pass'],
  },
  {
    id: 'crown-heart',
    name: 'Coeur de Couronne',
    grid: { col: 1, row: 0 },
    layout: { x: 38, y: 18, w: 23, h: 20 },
    labelLayout: { x: 49.5, y: 18.5, align: 'middle', tone: 'capital' },
    polygon: '24,18 40,12 58,14 64,24 58,40 40,46 26,38 22,28',
    ownerFactionId: 'aurora',
    controllingFactionId: 'aurora',
    supplyLevel: 'stable',
    loyalty: 78,
    strategicValue: 8,
    biome: 'temperate',
    terrain: 'plain',
    latitude: 42,
    resourceIds: ['grain', 'horses'],
    tags: ['capital', 'court'],
  },
  {
    id: 'red-ridge',
    name: 'Crête Rouge',
    grid: { col: 2, row: 0 },
    layout: { x: 64, y: 16, w: 21, h: 22 },
    labelLayout: { x: 75, y: 18.5, align: 'middle', tone: 'standard' },
    polygon: '58,16 73,10 88,18 90,34 80,44 64,42 54,32 52,22',
    ownerFactionId: 'ember',
    controllingFactionId: 'ember',
    supplyLevel: 'strained',
    loyalty: 58,
    strategicValue: 6,
    biome: 'arid',
    terrain: 'hills',
    altitudeMeters: 900,
    latitude: 37,
    resourceIds: ['ore', 'stone'],
    tags: ['ridge', 'fortified'],
  },
  {
    id: 'river-gate',
    name: 'Porte du Fleuve',
    grid: { col: 0, row: 1 },
    layout: { x: 22, y: 46, w: 24, h: 20 },
    labelLayout: { x: 21, y: 45, align: 'start', tone: 'frontier' },
    polygon: '38,38 54,34 66,40 68,54 56,66 40,64 32,52 34,42',
    ownerFactionId: 'aurora',
    controllingFactionId: 'ember',
    supplyLevel: 'disrupted',
    loyalty: 39,
    strategicValue: 7,
    contested: true,
    biome: 'coastal',
    terrain: 'river',
    coastal: true,
    latitude: 35,
    resourceIds: ['fish', 'clay'],
    hazards: [{ type: 'flood', riskLevel: 'high' }],
    tags: ['frontier', 'river-crossing', 'occupied'],
  },
  {
    id: 'iron-plain',
    name: 'Plaine de Fer',
    grid: { col: 1, row: 1 },
    layout: { x: 50, y: 46, w: 26, h: 22 },
    labelLayout: { x: 80, y: 48, align: 'end', tone: 'standard' },
    polygon: '60,44 78,42 90,52 88,68 72,78 56,72 54,56',
    ownerFactionId: 'ember',
    controllingFactionId: 'ember',
    supplyLevel: 'strained',
    loyalty: 61,
    strategicValue: 4,
    biome: 'temperate',
    terrain: 'plain',
    latitude: 31,
    resourceDeposits: { grain: 8, ore: 6 },
    tags: ['breadbasket', 'forges'],
  },
  {
    id: 'southern-reach',
    name: 'Basses Marches',
    grid: { col: 0, row: 2 },
    layout: { x: 33, y: 72, w: 28, h: 18 },
    labelLayout: { x: 47, y: 91, align: 'middle', tone: 'frontier' },
    polygon: '24,58 42,54 58,58 64,74 48,88 28,86 16,72',
    ownerFactionId: 'neutral',
    controllingFactionId: 'aurora',
    supplyLevel: 'collapsed',
    loyalty: 44,
    strategicValue: 3,
    biome: 'tropical',
    terrain: 'wetland',
    latitude: -12,
    resourceIds: ['fish', 'clay'],
    hazards: [{ type: 'disease', riskLevel: 'moderate' }],
    tags: ['marches', 'expedition-route', 'occupied'],
  },
]);

export const DEFAULT_STRATEGIC_MAP_LINKS = Object.freeze([
  ['north-watch', 'crown-heart'],
  ['north-watch', 'river-gate'],
  ['crown-heart', 'red-ridge'],
  ['crown-heart', 'river-gate'],
  ['crown-heart', 'iron-plain'],
  ['red-ridge', 'iron-plain'],
  ['river-gate', 'iron-plain'],
  ['river-gate', 'southern-reach'],
  ['iron-plain', 'southern-reach'],
]);
