import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const webAppSource = readFileSync(new URL('../../../web/app.js', import.meta.url), 'utf8');
const stylesSource = readFileSync(new URL('../../../web/styles.css', import.meta.url), 'utf8');

test('atlas world map canvas reuses existing province geometry for continents and islands', () => {
  assert.match(webAppSource, /function buildAtlasTerrainShapes/);
  assert.match(webAppSource, /getProvinceGeometry\(province\.provinceId\)/);
  assert.match(webAppSource, /getProvincePolygon\(province\.provinceId\)/);
  assert.match(webAppSource, /getProvinceCenter\(province\.provinceId\)/);
  assert.match(webAppSource, /const continents = shell\.provinces\.map/);
  assert.match(webAppSource, /islands/);
});

test('atlas world map canvas renders ocean terrain and relief as a dedicated map layer', () => {
  assert.match(webAppSource, /function renderAtlasWorldCanvas/);
  assert.match(webAppSource, /atlas-world-canvas/);
  assert.match(webAppSource, /atlasOceanGradient/);
  assert.match(webAppSource, /atlas-region--\$\{shape\.terrain\}/);
  assert.match(webAppSource, /map-layer--atlas/);
  assert.match(webAppSource, /renderAtlasWorldCanvas\(shell, economyView, cultureView\)/);
  assert.match(webAppSource, /function renderAtlasWorldEconomyLayer/);
  assert.match(webAppSource, /function buildAtlasEconomyStressRollups/);
  assert.match(webAppSource, /function buildAtlasSupplyCapacityForecasts/);
  assert.match(webAppSource, /function buildAtlasSupplyRouteCapacityForecast/);
  assert.match(webAppSource, /function buildAtlasCorridorInterventionOptions/);
  assert.match(webAppSource, /function buildAtlasCorridorActionBudget/);
  assert.match(webAppSource, /function buildAtlasCorridorBudgetShortfalls/);
  assert.match(webAppSource, /function buildAtlasFundedLogisticsPlans/);
  assert.match(webAppSource, /function buildAtlasCommittedFundingGaps/);
  assert.match(webAppSource, /function buildAtlasFundedCapacityProjections/);
  assert.match(webAppSource, /function renderAtlasEconomyStressLegend/);
  assert.match(webAppSource, /atlas-world-economy-layer/);
  assert.match(webAppSource, /atlas-economy-stress-rollup/);
  assert.match(webAppSource, /atlas-logistics-route/);
  assert.match(webAppSource, /atlas-economy-city/);
  assert.match(webAppSource, /Villes, ressources et flux logistiques sur la carte monde/);
  assert.match(webAppSource, /Légende économie atlas: stress logistique et régions économiques/);
  assert.match(webAppSource, /getAtlasEconomyCorridor/);
  assert.match(webAppSource, /routes saturés/);
  assert.match(webAppSource, /Sécuriser hub critique avant extension/);
  assert.match(webAppSource, /Capacité prochain tour/);
  assert.match(webAppSource, /risque surcharge prochain tour/);
  assert.match(webAppSource, /prévision incertaine/);
  assert.match(webAppSource, /Comparer interventions/);
  assert.match(webAppSource, /gain inconnu/);
  assert.match(webAppSource, /pénurie évitée élevée/);
  assert.match(webAppSource, /ex æquo/);
  assert.match(webAppSource, /Budget corridor/);
  assert.match(webAppSource, /Retenir:/);
  assert.match(webAppSource, /Reporter:/);
  assert.match(webAppSource, /Compromis:/);
  assert.match(webAppSource, /aucune intervention sûre/);
  assert.match(webAppSource, /coût inconnu/);
  assert.match(webAppSource, /Manques budget/);
  assert.match(webAppSource, /Aucun corridor sous-financé/);
  assert.match(webAppSource, /impact aval/);
  assert.match(webAppSource, /action minimale/);
  assert.match(webAppSource, /rediriger ressources/);
  assert.match(webAppSource, /réduire objectif/);
  assert.match(webAppSource, /Plan financé/);
  assert.match(webAppSource, /budget engagé/);
  assert.match(webAppSource, /reste à financer/);
  assert.match(webAppSource, /Aucun corridor finançable/);
  assert.match(webAppSource, /routes\/cités stabilisées/);
  assert.match(webAppSource, /Après engagement/);
  assert.match(webAppSource, /coût attendu/);
  assert.match(webAppSource, /écart restant/);
  assert.match(webAppSource, /risque résiduel moyen/);
  assert.match(webAppSource, /ressource stabilisée/);
  assert.match(webAppSource, /entièrement couvert/);
  assert.match(webAppSource, /reste à couvrir/);
  assert.match(webAppSource, /Capacité après plan/);
  assert.match(webAppSource, /financé et suffisant/);
  assert.match(webAppSource, /financé mais saturation possible/);
  assert.match(webAppSource, /financé partiellement, capacité à risque/);
  assert.match(webAppSource, /Revoir tour \+1/);
  assert.match(webAppSource, /priorité: compléter budget/);
  assert.match(webAppSource, /Aucune projection financée/);
  assert.match(webAppSource, /atlas-logistics-route--forecast-\$\{forecast\?\.tone \?\? 'unknown'\}/);
  assert.match(webAppSource, /getRouteStressSummary\(route, tensionByCityId, cityNameById\)/);
  assert.match(stylesSource, /\.atlas-world-canvas/);
  assert.match(stylesSource, /\.atlas-world-canvas__ocean-band/);
  assert.match(stylesSource, /\.atlas-region__relief/);
  assert.match(stylesSource, /\.atlas-island/);
  assert.match(stylesSource, /\.atlas-world-economy-layer/);
  assert.match(stylesSource, /\.atlas-economy-stress-rollup/);
  assert.match(stylesSource, /\.atlas-economy-region-rollup--critical/);
  assert.match(stylesSource, /\.atlas-economy-stress-legend--strained/);
  assert.match(stylesSource, /\.atlas-supply-forecast--overload/);
  assert.match(stylesSource, /\.atlas-supply-forecast__title/);
  assert.match(stylesSource, /\.atlas-logistics-route--forecast-uncertain/);
  assert.match(stylesSource, /\.atlas-corridor-intervention--overload/);
  assert.match(stylesSource, /\.atlas-corridor-intervention__rank/);
  assert.match(stylesSource, /\.atlas-corridor-budget/);
  assert.match(stylesSource, /\.atlas-corridor-budget__tradeoff/);
  assert.match(stylesSource, /\.atlas-corridor-shortfall/);
  assert.match(stylesSource, /\.atlas-corridor-shortfall-item--overload/);
  assert.match(stylesSource, /\.atlas-funded-logistics-plan/);
  assert.match(stylesSource, /\.atlas-funded-logistics-plan-item--partiel/);
  assert.match(stylesSource, /\.atlas-committed-funding-gap/);
  assert.match(stylesSource, /\.atlas-committed-funding-gap-item--gap/);
  assert.match(stylesSource, /\.atlas-committed-funding-gap-item--covered/);
  assert.match(stylesSource, /\.atlas-funded-capacity-projection/);
  assert.match(stylesSource, /\.atlas-funded-capacity-projection-item--saturated/);
  assert.match(stylesSource, /\.atlas-funded-capacity-projection-item--sufficient/);
  assert.match(stylesSource, /\.atlas-logistics-route--major/);
  assert.match(stylesSource, /\.atlas-economy-city--high/);
  assert.match(stylesSource, /\.atlas-economy-city__resources/);
});
