import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const webAppSource = readFileSync(new URL('../../../web/app.js', import.meta.url), 'utf8');
const stylesSource = readFileSync(new URL('../../../web/styles.css', import.meta.url), 'utf8');

test('atlas world map canvas reuses existing province geometry for continents and islands', () => {
  assert.match(webAppSource, /function buildAtlasTerrainShapes/);
  assert.match(webAppSource, /getProvinceGeometry\(province\.provinceId\)/);
  assert.match(webAppSource, /getProvincePolygon\(province\.provinceId\)/);
  assert.match(webAppSource, /getProvinceCenter\(province\.provinceId\)/);
  assert.match(webAppSource, /const continents = shell\.provinces\.map/);
  assert.match(webAppSource, /islands/);
});

test('atlas world map canvas renders ocean terrain and relief as a dedicated map layer', () => {
  assert.match(webAppSource, /function renderAtlasWorldCanvas/);
  assert.match(webAppSource, /atlas-world-canvas/);
  assert.match(webAppSource, /atlasOceanGradient/);
  assert.match(webAppSource, /atlas-region--\$\{shape\.terrain\}/);
  assert.match(webAppSource, /map-layer--atlas/);
  assert.match(webAppSource, /renderAtlasWorldCanvas\(shell, economyView, cultureView\)/);
  assert.match(webAppSource, /function renderAtlasWorldEconomyLayer/);
  assert.match(webAppSource, /function buildAtlasEconomyStressRollups/);
  assert.match(webAppSource, /function buildAtlasSupplyCapacityForecasts/);
  assert.match(webAppSource, /function buildAtlasSupplyRouteCapacityForecast/);
  assert.match(webAppSource, /function buildAtlasCorridorInterventionOptions/);
  assert.match(webAppSource, /function buildAtlasCorridorActionBudget/);
  assert.match(webAppSource, /function buildAtlasCorridorBudgetShortfalls/);
  assert.match(webAppSource, /function buildAtlasFundedLogisticsPlans/);
  assert.match(webAppSource, /function buildAtlasCommittedFundingGaps/);
  assert.match(webAppSource, /function buildAtlasFundedCapacityProjections/);
  assert.match(webAppSource, /function buildAtlasSecondaryBottleneckReroute/);
  assert.match(webAppSource, /function buildAtlasSecondaryBottleneckRerouteReadiness/);
  assert.match(webAppSource, /function buildAtlasSecondaryBottlenecks/);
  assert.match(webAppSource, /function renderAtlasEconomyStressLegend/);
  assert.match(webAppSource, /atlas-world-economy-layer/);
  assert.match(webAppSource, /atlas-economy-stress-rollup/);
  assert.match(webAppSource, /atlas-logistics-route/);
  assert.match(webAppSource, /atlas-economy-city/);
  assert.match(webAppSource, /Villes, ressources et flux logistiques sur la carte monde/);
  assert.match(webAppSource, /Légende économie atlas: stress logistique et régions économiques/);
  assert.match(webAppSource, /getAtlasEconomyCorridor/);
  assert.match(webAppSource, /routes saturés/);
  assert.match(webAppSource, /Sécuriser hub critique avant extension/);
  assert.match(webAppSource, /Capacité prochain tour/);
  assert.match(webAppSource, /risque surcharge prochain tour/);
  assert.match(webAppSource, /prévision incertaine/);
  assert.match(webAppSource, /Comparer interventions/);
  assert.match(webAppSource, /gain inconnu/);
  assert.match(webAppSource, /pénurie évitée élevée/);
  assert.match(webAppSource, /ex æquo/);
  assert.match(webAppSource, /Budget corridor/);
  assert.match(webAppSource, /Retenir:/);
  assert.match(webAppSource, /Reporter:/);
  assert.match(webAppSource, /Compromis:/);
  assert.match(webAppSource, /aucune intervention sûre/);
  assert.match(webAppSource, /coût inconnu/);
  assert.match(webAppSource, /Manques budget/);
  assert.match(webAppSource, /Aucun corridor sous-financé/);
  assert.match(webAppSource, /impact aval/);
  assert.match(webAppSource, /action minimale/);
  assert.match(webAppSource, /rediriger ressources/);
  assert.match(webAppSource, /réduire objectif/);
  assert.match(webAppSource, /Plan financé/);
  assert.match(webAppSource, /budget engagé/);
  assert.match(webAppSource, /reste à financer/);
  assert.match(webAppSource, /Aucun corridor finançable/);
  assert.match(webAppSource, /routes\/cités stabilisées/);
  assert.match(webAppSource, /Après engagement/);
  assert.match(webAppSource, /coût attendu/);
  assert.match(webAppSource, /écart restant/);
  assert.match(webAppSource, /risque résiduel moyen/);
  assert.match(webAppSource, /ressource stabilisée/);
  assert.match(webAppSource, /entièrement couvert/);
  assert.match(webAppSource, /reste à couvrir/);
  assert.match(webAppSource, /Capacité après plan/);
  assert.match(webAppSource, /financé et suffisant/);
  assert.match(webAppSource, /financé mais saturation possible/);
  assert.match(webAppSource, /financé partiellement, capacité à risque/);
  assert.match(webAppSource, /Revoir tour \+1/);
  assert.match(webAppSource, /priorité: compléter budget/);
  assert.match(webAppSource, /Aucune projection financée/);
  assert.match(webAppSource, /Prochains goulets/);
  assert.match(webAppSource, /Aucun goulet secondaire pertinent/);
  assert.match(webAppSource, /nouveau goulet secondaire/);
  assert.match(webAppSource, /encore saturé/);
  assert.match(webAppSource, /résolu/);
  assert.match(webAppSource, /ralentit le bénéfice financé/);
  assert.match(webAppSource, /dériver via/);
  assert.match(webAppSource, /dérivation non disponible/);
  assert.match(webAppSource, /voisins déjà saturés/);
  assert.match(webAppSource, /consomme marge financée/);
  assert.match(webAppSource, /prêt maintenant/);
  assert.match(webAppSource, /bloqué financement/);
  assert.match(webAppSource, /bloqué capacité/);
  assert.match(webAppSource, /bloqué risque/);
  assert.match(webAppSource, /financement, capacité et risque OK/);
  assert.match(webAppSource, /marge voisine encore à financer/);
  assert.match(webAppSource, /aucun voisin avec marge exécutable/);
  assert.match(webAppSource, /instabilité régionale à qualifier/);
  assert.match(webAppSource, /unblockAction/);
  assert.match(webAppSource, /Action: \$\{item\.readiness\.unblockAction\}/);
  assert.match(webAppSource, /ajouter \$\{Math\.max\(1, fundingGap\)\} budget corridor/);
  assert.match(webAppSource, /libérer \+\$\{capacityGap\} capacité hub voisin/);
  assert.match(webAppSource, /stabiliser \$\{unstableHubs\} hub/);
  assert.match(webAppSource, /tradeoffComparison/);
  assert.match(webAppSource, /compareFundingVsCapacity/);
  assert.match(webAppSource, /compareRiskVsBudget/);
  assert.match(webAppSource, /choisir \$\{selected\}; écarter \$\{rejected\}/);
  assert.match(webAppSource, /moins cher que délestage voisin/);
  assert.match(webAppSource, /corrige la contrainte de marge/);
  assert.match(webAppSource, /réduit le risque avant dépense/);
  assert.match(webAppSource, /Vs: \$\{item\.readiness\.tradeoffComparison\.rejected\}/);
  assert.match(webAppSource, /function buildAtlasSecondaryBottleneckExecuteVerdict/);
  assert.match(webAppSource, /executeVerdict/);
  assert.match(webAppSource, /execute-now/);
  assert.match(webAppSource, /wait-for-budget/);
  assert.match(webAppSource, /wait-for-capacity/);
  assert.match(webAppSource, /too-risky/);
  assert.match(webAppSource, /exécuter maintenant/);
  assert.match(webAppSource, /attendre budget/);
  assert.match(webAppSource, /attendre capacité/);
  assert.match(webAppSource, /attendre: trop risqué/);
  assert.match(webAppSource, /selectedAction/);
  assert.match(webAppSource, /rejectedAlternative/);
  assert.match(webAppSource, /routeStress/);
  assert.match(webAppSource, /budgetPressure/);
  assert.match(webAppSource, /hubCapacityPressure/);
  assert.match(webAppSource, /instabilityRisk/);
  assert.match(webAppSource, /index > 0 \|\| item\.readiness\.status === 'ready' \|\| !item\.readiness\.unblockAction/);
  assert.match(webAppSource, /Verdict: \$\{item\.executeVerdict\.label\}/);
  assert.match(webAppSource, /buildReadiness\(\n    'ready',[\s\S]*?financement, capacité et risque OK[\s\S]*?\);/);
  assert.match(webAppSource, /atlas-logistics-route--forecast-\$\{forecast\?\.tone \?\? 'unknown'\}/);
  assert.match(webAppSource, /getRouteStressSummary\(route, tensionByCityId, cityNameById\)/);
  assert.match(stylesSource, /\.atlas-world-canvas/);
  assert.match(stylesSource, /\.atlas-world-canvas__ocean-band/);
  assert.match(stylesSource, /\.atlas-region__relief/);
  assert.match(stylesSource, /\.atlas-island/);
  assert.match(stylesSource, /\.atlas-world-economy-layer/);
  assert.match(stylesSource, /\.atlas-economy-stress-rollup/);
  assert.match(stylesSource, /\.atlas-economy-region-rollup--critical/);
  assert.match(stylesSource, /\.atlas-economy-stress-legend--strained/);
  assert.match(stylesSource, /\.atlas-supply-forecast--overload/);
  assert.match(stylesSource, /\.atlas-supply-forecast__title/);
  assert.match(stylesSource, /\.atlas-logistics-route--forecast-uncertain/);
  assert.match(stylesSource, /\.atlas-corridor-intervention--overload/);
  assert.match(stylesSource, /\.atlas-corridor-intervention__rank/);
  assert.match(stylesSource, /\.atlas-corridor-budget/);
  assert.match(stylesSource, /\.atlas-corridor-budget__tradeoff/);
  assert.match(stylesSource, /\.atlas-corridor-shortfall/);
  assert.match(stylesSource, /\.atlas-corridor-shortfall-item--overload/);
  assert.match(stylesSource, /\.atlas-funded-logistics-plan/);
  assert.match(stylesSource, /\.atlas-funded-logistics-plan-item--partiel/);
  assert.match(stylesSource, /\.atlas-committed-funding-gap/);
  assert.match(stylesSource, /\.atlas-committed-funding-gap-item--gap/);
  assert.match(stylesSource, /\.atlas-committed-funding-gap-item--covered/);
  assert.match(stylesSource, /\.atlas-funded-capacity-projection/);
  assert.match(stylesSource, /\.atlas-funded-capacity-projection-item--saturated/);
  assert.match(stylesSource, /\.atlas-funded-capacity-projection-item--sufficient/);
  assert.match(stylesSource, /\.atlas-secondary-bottleneck/);
  assert.match(stylesSource, /\.atlas-secondary-bottleneck-item--secondary/);
  assert.match(stylesSource, /\.atlas-secondary-bottleneck-item--resolved/);
  assert.match(stylesSource, /\.atlas-secondary-bottleneck-item__reroute/);
  assert.match(stylesSource, /\.atlas-secondary-bottleneck-item__readiness/);
  assert.match(stylesSource, /\.atlas-secondary-bottleneck-item\.has-reroute/);
  assert.match(stylesSource, /\.atlas-secondary-bottleneck-item--ready/);
  assert.match(stylesSource, /\.atlas-secondary-bottleneck-item--blocked-funding/);
  assert.match(stylesSource, /\.atlas-secondary-bottleneck-item--blocked-capacity/);
  assert.match(stylesSource, /\.atlas-secondary-bottleneck-item--blocked-risk/);
  assert.match(stylesSource, /\.atlas-logistics-route--major/);
  assert.match(stylesSource, /\.atlas-economy-city--high/);
  assert.match(stylesSource, /\.atlas-economy-city__resources/);
});
