import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const webAppSource = readFileSync(new URL('../../../web/app.js', import.meta.url), 'utf8');
const stylesSource = readFileSync(new URL('../../../web/styles.css', import.meta.url), 'utf8');

test('atlas military fallback order hint builds on top warning best order and relief data', () => {
  assert.match(webAppSource, /function buildAtlasMilitaryFallbackOrderHint\(priorityStack, orderHint, reliefPreview, commitment, shell\)/);
  assert.match(webAppSource, /getAtlasMilitaryBestOrderBlocker\(topWarning, orderHint, reliefPreview, commitment\)/);
  assert.match(webAppSource, /buildAtlasMilitaryFallbackOrderHint\(priorityStack, bestOrderHint, topReliefPreview, commitment, shell\)/);
  assert.match(webAppSource, /renderAtlasMilitaryFallbackOrderHint\(fallbackOrderHint\)/);
});

test('atlas military fallback order hint handles resource route overcommitment and cross-domain blocks', () => {
  assert.match(webAppSource, /return 'resource-blocked'/);
  assert.match(webAppSource, /return 'route-blocked'/);
  assert.match(webAppSource, /return 'overcommitment-blocked'/);
  assert.match(webAppSource, /order: 'Fixer réserve'/);
  assert.match(webAppSource, /order: 'Sécuriser détour'/);
  assert.match(webAppSource, /order: 'Geler engagement'/);
  assert.match(webAppSource, /detail: `réduire la charge sur \$\{commitment\?\.selectedOption\?\.target \?\? topWarning\?\.label\}`/);
  assert.match(webAppSource, /type: 'avoids-overcommitment'/);
  assert.match(webAppSource, /type: 'bypasses-route-exposure'/);
  assert.match(webAppSource, /type: 'preserves-front-coverage'/);
  assert.match(webAppSource, /type: 'waits-for-resupply'/);
  assert.match(webAppSource, /type: 'no-clear-safety-reason'/);
  assert.match(webAppSource, /type: 'budget-logistics'/);
  assert.match(webAppSource, /type: 'intrigue-exposure'/);
  assert.match(webAppSource, /type: 'cultural-tension'/);
  assert.match(webAppSource, /type: 'climate-pressure'/);
  assert.match(webAppSource, /type: 'no-clear-cross-domain-blocker'/);
  assert.match(webAppSource, /function buildAtlasMilitaryFallbackSelectionPreview\(fallback, topWarning, reliefPreview\)/);
  assert.match(webAppSource, /type: 'front-stabilized'/);
  assert.match(webAppSource, /type: 'exposure-reduced'/);
  assert.match(webAppSource, /type: 'capacity-freed'/);
  assert.match(webAppSource, /type: 'reinforcement-window-opened'/);
  assert.match(webAppSource, /type: 'no-safe-visible-change'/);
  assert.match(webAppSource, /function buildAtlasMilitaryFallbackResidualRisks\(fallback, topWarning, shell, priorityStack\)/);
  assert.match(webAppSource, /key: `neighbor-front:\$\{lowerWarning\.sourceId \?\? lowerWarning\.debtId\}`/);
  assert.match(webAppSource, /label: 'front voisin fragile'/);
  assert.match(webAppSource, /key: `contested-occupation:\$\{province\.provinceId\}`/);
  assert.match(webAppSource, /label: 'occupation contestée'/);
  assert.match(webAppSource, /key: `low-loyalty:\$\{province\.provinceId\}`/);
  assert.match(webAppSource, /label: 'loyauté basse'/);
  assert.match(webAppSource, /key: `supply-pressure:\$\{province\.provinceId\}`/);
  assert.match(webAppSource, /label: 'pression ravitaillement'/);
  assert.match(webAppSource, /key: `route-exposure:\$\{topWarning\.sourceId\}`/);
  assert.match(webAppSource, /label: 'axe encore exposé'/);
  assert.match(webAppSource, /function buildAtlasMilitaryFallbackCleanupOrders\(residualRisks, fallback\)/);
  assert.match(webAppSource, /id: `cleanup:\$\{fallback\.type\}:\$\{risk\.key\}`/);
  assert.match(webAppSource, /label: 'Caler couverture voisine'/);
  assert.match(webAppSource, /label: 'Stabiliser occupation'/);
  assert.match(webAppSource, /label: 'Envoyer liaison locale'/);
  assert.match(webAppSource, /label: 'Prioriser convoi court'/);
  assert.match(webAppSource, /label: 'Scanner axe détour'/);
  assert.match(webAppSource, /residualRiskKey: risk\.key/);
  assert.match(webAppSource, /riskReduced: risk\.label/);
  assert.match(webAppSource, /prerequisite: cleanup\.prerequisite/);
  assert.match(webAppSource, /safetyScore/);
  assert.match(webAppSource, /buildFirstCleanupPayoff\(cleanupOrders, residualRisks\)/);
  assert.match(webAppSource, /buildFollowUpCleanupChoices\(cleanupOrders, residualRisks, firstCleanupPayoff\)/);
  assert.match(webAppSource, /buildTopFollowUpReadiness\(followUpCleanupChoices, residualRisks\)/);
  assert.match(webAppSource, /buildFollowUpCleanupMiniPlan\(followUpCleanupChoices, residualRisks, topFollowUpReadiness\)/);
  assert.match(webAppSource, /buildMiniPlanDependencyConflicts\(/);
  assert.match(webAppSource, /buildMiniPlanConflictTradeoffs\(/);
  assert.match(webAppSource, /buildMiniPlanTradeoffActionPreview\(/);
  assert.match(webAppSource, /buildMiniPlanRivalResponseRisk\(/);
  assert.match(webAppSource, /buildMiniPlanRivalResponseComparison\(/);
  assert.match(webAppSource, /buildMiniPlanRivalResponseFallback\(/);
  assert.match(webAppSource, /buildMiniPlanFallbackReturnCue\(/);
  assert.match(webAppSource, /buildMiniPlanReturnProtectionStatus\(/);
  assert.match(webAppSource, /buildMiniPlanConfidenceSignalCue\(/);
  assert.match(webAppSource, /buildMiniPlanDecisionReversibilityCue\(/);
  assert.match(webAppSource, /firstCleanupPayoff/);
  assert.match(webAppSource, /followUpCleanupChoices/);
  assert.match(webAppSource, /topFollowUpReadiness/);
});

test('atlas military fallback order hint stays secondary and hides no-safe fallback state', () => {
  assert.match(webAppSource, /Aucun fallback sûr: ordre principal non bloqué ou alternative trop risquée/);
  assert.match(webAppSource, /return 'no-safe-fallback'/);
  assert.match(webAppSource, /if \(!fallbackHint \|\| fallbackHint\.empty \|\| !fallbackHint\.fallback\) return ''/);
  assert.match(webAppSource, /data-atlas-fallback-order/);
  assert.match(webAppSource, /atlas-military-fallback-order__safety/);
  assert.match(webAppSource, /atlas-military-fallback-order__blocker/);
  assert.match(webAppSource, /fallback\.crossDomainBlocker \? `<text class="atlas-military-fallback-order__blocker"/);
  assert.match(webAppSource, /crossDomainBlocker: null/);
  assert.match(webAppSource, /selectionPreview: null/);
  assert.match(webAppSource, /residualRisks: \[\]/);
  assert.match(webAppSource, /cleanupOrders: \[\]/);
  assert.match(webAppSource, /residualRisks\.length \? `; risques restants: \$\{residualRisks\.map\(\(risk\) => risk\.label\)\.join\(', '\)\}` : '; risques restants: aucun visible'/);
  assert.match(webAppSource, /cleanupOrders\.length \? `; nettoyage: \$\{cleanupOrders\[0\]\.label\}` : '; nettoyage: aucun requis'/);
  assert.match(webAppSource, /fallback\.selectionPreview \? `<text class="atlas-military-fallback-order__preview/);
  assert.match(webAppSource, /atlas-military-fallback-order__residual-risks/);
  assert.match(webAppSource, /atlas-military-fallback-order__cleanup-orders/);
  assert.match(webAppSource, /reste: aucun risque visible/);
  assert.match(webAppSource, /nettoyer: aucun ordre requis/);
  assert.match(webAppSource, /payoff: aucun nettoyage utile/);
  assert.match(webAppSource, /suivi: aucun cleanup utile/);
  assert.match(webAppSource, /readiness: aucun suivi sûr/);
  assert.match(webAppSource, /plan: aucun suivi sûr/);
  assert.match(webAppSource, /conflits: aucun visible/);
  assert.match(webAppSource, /miniPlanDependencyConflicts: \[\]/);
  assert.match(webAppSource, /miniPlanConflictTradeoffs: \[\]/);
  assert.match(webAppSource, /choix: aucun arbitrage/);
  assert.match(webAppSource, /action: aucun arbitrage prêt/);
  assert.match(webAppSource, /miniPlanTradeoffActionPreview: buildMiniPlanTradeoffActionPreview\(null, \[\]\)/);
  assert.match(webAppSource, /miniPlanRivalResponseRisk: buildMiniPlanRivalResponseRisk\(buildMiniPlanTradeoffActionPreview\(null, \[\]\), \[\]\)/);
  assert.match(webAppSource, /miniPlanRivalResponseComparison: buildMiniPlanRivalResponseComparison\(null, \[\]\)/);
  assert.match(webAppSource, /miniPlanRivalResponseFallback: buildMiniPlanRivalResponseFallback\(buildMiniPlanRivalResponseComparison\(null, \[\]\)\)/);
  assert.match(webAppSource, /miniPlanFallbackReturnCue: buildMiniPlanFallbackReturnCue\(/);
  assert.match(webAppSource, /miniPlanReturnProtectionStatus: buildMiniPlanReturnProtectionStatus\(/);
  assert.match(webAppSource, /miniPlanConfidenceSignalCue: buildMiniPlanConfidenceSignalCue\(/);
  assert.match(webAppSource, /miniPlanDecisionReversibilityCue: buildMiniPlanDecisionReversibilityCue\(/);
  assert.match(webAppSource, /Risque si: aucun rival lisible/);
  assert.match(webAppSource, /branches: aucune comparaison/);
  assert.match(webAppSource, /fallback: aucun repli requis/);
  assert.match(webAppSource, /retour: aucun arbitrage/);
  assert.match(webAppSource, /protection retour: non évaluée/);
  assert.match(webAppSource, /confiance: non évaluée/);
  assert.match(webAppSource, /réversibilité: non évaluée/);
  assert.match(webAppSource, /atlas-military-fallback-order__cleanup-payoff/);
  assert.match(webAppSource, /atlas-military-fallback-order__cleanup-followups/);
  assert.match(webAppSource, /atlas-military-fallback-order__followup-readiness/);
  assert.match(webAppSource, /atlas-military-fallback-order__mini-plan/);
  assert.match(webAppSource, /atlas-military-fallback-order__mini-plan-conflicts/);
  assert.match(webAppSource, /atlas-military-fallback-order__mini-plan-tradeoffs/);
  assert.match(webAppSource, /atlas-military-fallback-order__tradeoff-action/);
  assert.match(webAppSource, /atlas-military-fallback-order__rival-response-risk/);
  assert.match(webAppSource, /atlas-military-fallback-order__rival-branch-comparison/);
  assert.match(webAppSource, /atlas-military-fallback-order__rival-response-fallback/);
  assert.match(webAppSource, /atlas-military-fallback-order__fallback-return-cue/);
  assert.match(webAppSource, /atlas-military-fallback-order__return-protection/);
  assert.match(webAppSource, /atlas-military-fallback-order__confidence-signal/);
  assert.match(webAppSource, /atlas-military-fallback-order__decision-reversibility/);
  assert.match(webAppSource, /payoff: \$\{fallback\.firstCleanupPayoff\.riskReduced\} ↓ · reste \$\{fallback\.firstCleanupPayoff\.remainingRiskCount\}/);
  assert.match(webAppSource, /suivi: \$\{fallback\.followUpCleanupChoices\.map\(\(choice\) => `\$\{choice\.rank\}\. \$\{choice\.cleanupOrderLabel\} \(\$\{choice\.riskCovered\}\)`\)\.join\(' · '\)\}/);
  assert.match(webAppSource, /readiness: \$\{fallback\.topFollowUpReadiness\.label\} · \$\{fallback\.topFollowUpReadiness\.blocker\}/);
  assert.match(webAppSource, /plan: \$\{miniPlan\.steps\.map\(\(step\) => `\$\{step\.order\}\.\$\{step\.label\} › \$\{step\.riskReduced\}; reste \$\{step\.untreatedRisk\}`\)\.join\(' · '\)\}/);
  assert.match(webAppSource, /conflits: \$\{dependencyConflicts\.map\(\(conflict\) => `\$\{conflict\.severity === 'blocking' \? 'bloquant' : 'surv\.'\} \$\{conflict\.label\} › \$\{conflict\.mitigation\}`\)\.join\(' · '\)\}/);
  assert.match(webAppSource, /choix: \$\{tradeoffs\.map\(\(tradeoff\) => `\$\{tradeoff\.severity === 'blocking' \? '★' : '○'\} \$\{tradeoff\.recommendedChoice\} \/ coût: \$\{tradeoff\.rejectedCost\}`\)\.join\(' · '\)\}/);
  assert.match(webAppSource, /action: \$\{actionPreview\.action\} @ \$\{actionPreview\.targetId \?\? 'front'\} · préreq \$\{actionPreview\.prerequisite\} · gain \$\{actionPreview\.expectedBenefit\}/);
  assert.match(webAppSource, /Risque si: \$\{rivalRisk\.response\} · \$\{rivalRisk\.label\} · \$\{rivalRisk\.watch\}/);
  assert.match(webAppSource, /branches: \$\{rivalComparison\.branches\.map\(\(branch\) => `\$\{branch\.recommended \? '★' : '○'\} \$\{branch\.action\} → \$\{branch\.rivalResponse\} \(\$\{branch\.riskLevel\}\)`\)\.join\(' · '\)\}\$\{rivalComparison\.recommendationChanged \? ' · reco change' : ' · reco stable'\}/);
  assert.match(webAppSource, /fallback: \$\{rivalFallback\.action\} @ \$\{rivalFallback\.targetId \?\? 'front'\} · \$\{rivalFallback\.reason\} · coût \$\{rivalFallback\.cost\}/);
  assert.match(webAppSource, /\$\{fallbackReturnCue\.decision === 'keep-fallback' \? 'garder fallback' : 'retour initial'\}: \$\{fallbackReturnCue\.condition\} · coût \$\{fallbackReturnCue\.switchCost\}/);
  assert.match(webAppSource, /\$\{returnProtection\.label\}: \$\{returnProtection\.constraint\} · \$\{returnProtection\.nextDecision\}/);
  assert.match(webAppSource, /\$\{confidenceSignal\.label\}: \$\{confidenceSignal\.signal\} · \$\{confidenceSignal\.waitCost\}/);
  assert.match(webAppSource, /réversibilité: \$\{reversibility\.label\} · \$\{reversibility\.constraint\}\$\{reversibility\.nextStep \? ` · \$\{reversibility\.nextStep\}` : ''\}/);
  assert.match(webAppSource, /crossDomainBlocker \? `; \$\{crossDomainBlocker\.label\}` : ''/);
  assert.match(webAppSource, /selectionPreview \? `; \$\{selectionPreview\.label\}` : ''/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__panel/);
  assert.match(stylesSource, /\.atlas-military-fallback-order--route-blocked/);
  assert.match(stylesSource, /\.atlas-military-fallback-order--overcommitment-blocked/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__safety/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__blocker/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__preview/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__residual-risks/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__cleanup-orders/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__cleanup-payoff/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__cleanup-followups/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__followup-readiness/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__mini-plan/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__mini-plan-conflicts/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__mini-plan-tradeoffs/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__tradeoff-action/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__rival-response-risk/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__rival-branch-comparison/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__rival-response-fallback/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__fallback-return-cue/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__return-protection/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__confidence-signal/);
  assert.match(stylesSource, /\.atlas-military-fallback-order__decision-reversibility/);
});
