import test from 'node:test';
import assert from 'node:assert/strict';

import { Culture } from '../../../src/domain/culture/Culture.js';
import { HistoricalEvent } from '../../../src/domain/culture/HistoricalEvent.js';
import { ResearchState } from '../../../src/domain/culture/ResearchState.js';
import { buildCultureMapOverlay } from '../../../src/ui/culture/buildCultureMapOverlay.js';

test('buildCultureMapOverlay expands cultures into stable regional markers with discoveries', () => {
  const overlay = buildCultureMapOverlay(
    {
      cultures: [
        new Culture({
          id: 'culture-north',
          name: 'Northern League',
          archetype: 'maritime',
          primaryLanguage: 'north-tongue',
          valueIds: ['trade', 'navigation'],
          traditionIds: ['assemblies'],
          openness: 72,
          cohesion: 61,
          researchDrive: 77,
        }),
        new Culture({
          id: 'culture-steppe',
          name: 'Steppe Houses',
          archetype: 'nomadic',
          primaryLanguage: 'horse-speech',
          valueIds: ['honor'],
          traditionIds: ['clan-oaths'],
          openness: 35,
          cohesion: 67,
          researchDrive: 40,
        }),
      ],
      researchStates: [
        new ResearchState({
          id: 'research-astrolabe',
          cultureId: 'culture-north',
          topicId: 'astrolabe',
          status: 'active',
          progress: 65,
          discoveredConceptIds: ['star-maps', 'tidal-ledgers'],
        }),
        new ResearchState({
          id: 'research-saddles',
          cultureId: 'culture-steppe',
          topicId: 'composite-saddles',
          status: 'completed',
          progress: 100,
          completedAt: '2026-04-19T00:00:00.000Z',
          discoveredConceptIds: ['stirrup-drill'],
        }),
      ],
      historicalEvents: [
        new HistoricalEvent({
          id: 'event-open-archives',
          title: 'Open Archives',
          category: 'knowledge',
          summary: 'Scholars share navigation routes.',
          era: 'age-of-sails',
          importance: 3,
          triggeredAt: '2026-04-19T00:00:00.000Z',
          affectedCultureIds: ['culture-north'],
          discoveryIds: ['public-catalogue'],
        }),
      ],
    },
    {
      regionIdsByCulture: {
        'culture-north': ['north-coast', 'archipelago'],
        'culture-steppe': ['high-steppe'],
      },
    },
  );

  assert.deepEqual(overlay, [
    {
      overlayId: 'archipelago:culture-north',
      regionId: 'archipelago',
      cultureId: 'culture-north',
      cultureName: 'Northern League',
      archetype: 'maritime',
      primaryLanguage: 'north-tongue',
      markerType: 'innovation',
      influenceScore: 79,
      influenceTier: 'strong',
      label: 'Northern League (3 découvertes)',
      summary: '1 recherches actives, 1 événements, 3 repères culturels',
      discoveries: ['public-catalogue', 'star-maps', 'tidal-ledgers'],
      regionalDiscoveryLinks: [
        {
          linkId: 'archipelago:culture-north:public-catalogue',
          regionId: 'archipelago',
          cultureId: 'culture-north',
          discoveryId: 'public-catalogue',
          eventIds: ['event-open-archives'],
          eventTitles: ['Open Archives'],
          eventCount: 1,
          activeResearchCount: 1,
          label: 'public-catalogue · archipelago · 1 événement',
        },
        {
          linkId: 'archipelago:culture-north:star-maps',
          regionId: 'archipelago',
          cultureId: 'culture-north',
          discoveryId: 'star-maps',
          eventIds: [],
          eventTitles: [],
          eventCount: 0,
          activeResearchCount: 1,
          label: 'star-maps · archipelago',
        },
        {
          linkId: 'archipelago:culture-north:tidal-ledgers',
          regionId: 'archipelago',
          cultureId: 'culture-north',
          discoveryId: 'tidal-ledgers',
          eventIds: [],
          eventTitles: [],
          eventCount: 0,
          activeResearchCount: 1,
          label: 'tidal-ledgers · archipelago',
        },
      ],
      unlockedResearchIds: ['astrolabe'],
      activeResearchCount: 1,
      eventIds: ['event-open-archives'],
      eventTitles: ['Open Archives'],
      eventCount: 1,
      eventPopups: [
        {
          popupId: 'archipelago:culture-north:event-open-archives:popup',
          eventId: 'event-open-archives',
          title: 'Open Archives',
          summary: 'Scholars share navigation routes.',
          triggeredAt: '2026-04-19T00:00:00.000Z',
          importance: 3,
          discoveries: ['public-catalogue'],
          unlockedResearchIds: ['astrolabe'],
          label: 'Open Archives · 2026-04-19',
          order: 1,
        },
      ],
      identityTags: ['assemblies', 'navigation', 'trade'],
      highlights: ['public-catalogue', 'star-maps', 'assemblies'],
      cultureMetrics: {
        openness: 72,
        cohesion: 61,
        researchDrive: 77,
      },
      zoneRank: 0,
      overlapCount: 1,
      zoneBand: 'core',
      dominantInRegion: true,
      competingCultureIds: [],
      zoneContour: {
        radius: 22,
        feather: 2,
        ringCount: 1,
      },
      style: {
        color: 'violet',
        icon: '✦',
        emphasis: 'high',
        accent: 'iris',
        labelTone: 'visionary',
      },
      zoneStyle: {
        fill: 'violet',
        outline: 'violet',
        accent: 'iris',
        markerIcon: '✦',
        emphasis: 'high',
        labelTone: 'visionary',
        opacity: 0.7,
        pattern: 'radiant',
        surface: 'gloss',
        glow: 'luminous',
        blendMode: 'source-over',
        strokeWidth: 4,
      },
    },
    {
      overlayId: 'high-steppe:culture-steppe',
      regionId: 'high-steppe',
      cultureId: 'culture-steppe',
      cultureName: 'Steppe Houses',
      archetype: 'nomadic',
      primaryLanguage: 'horse-speech',
      markerType: 'traditional',
      influenceScore: 45,
      influenceTier: 'emerging',
      label: 'Steppe Houses (1 découvertes)',
      summary: '0 recherches actives, 0 événements, 2 repères culturels',
      discoveries: ['stirrup-drill'],
      regionalDiscoveryLinks: [
        {
          linkId: 'high-steppe:culture-steppe:stirrup-drill',
          regionId: 'high-steppe',
          cultureId: 'culture-steppe',
          discoveryId: 'stirrup-drill',
          eventIds: [],
          eventTitles: [],
          eventCount: 0,
          activeResearchCount: 0,
          label: 'stirrup-drill · high-steppe',
        },
      ],
      unlockedResearchIds: ['composite-saddles'],
      activeResearchCount: 0,
      eventIds: [],
      eventTitles: [],
      eventCount: 0,
      eventPopups: [],
      identityTags: ['clan-oaths', 'honor'],
      highlights: ['stirrup-drill', 'clan-oaths', 'honor'],
      cultureMetrics: {
        openness: 35,
        cohesion: 67,
        researchDrive: 40,
      },
      zoneRank: 0,
      overlapCount: 1,
      zoneBand: 'core',
      dominantInRegion: true,
      competingCultureIds: [],
      zoneContour: {
        radius: 18,
        feather: 2,
        ringCount: 1,
      },
      style: {
        color: 'amber',
        icon: '⬢',
        emphasis: 'normal',
        accent: 'ochre',
        labelTone: 'ancestral',
      },
      zoneStyle: {
        fill: 'amber',
        outline: 'amber',
        accent: 'ochre',
        markerIcon: '⬢',
        emphasis: 'normal',
        labelTone: 'ancestral',
        opacity: 0.55,
        pattern: 'woven',
        surface: 'grain',
        glow: 'matte',
        blendMode: 'source-over',
        strokeWidth: 4,
      },
    },
    {
      overlayId: 'north-coast:culture-north',
      regionId: 'north-coast',
      cultureId: 'culture-north',
      cultureName: 'Northern League',
      archetype: 'maritime',
      primaryLanguage: 'north-tongue',
      markerType: 'innovation',
      influenceScore: 79,
      influenceTier: 'strong',
      label: 'Northern League (3 découvertes)',
      summary: '1 recherches actives, 1 événements, 3 repères culturels',
      discoveries: ['public-catalogue', 'star-maps', 'tidal-ledgers'],
      regionalDiscoveryLinks: [
        {
          linkId: 'north-coast:culture-north:public-catalogue',
          regionId: 'north-coast',
          cultureId: 'culture-north',
          discoveryId: 'public-catalogue',
          eventIds: ['event-open-archives'],
          eventTitles: ['Open Archives'],
          eventCount: 1,
          activeResearchCount: 1,
          label: 'public-catalogue · north-coast · 1 événement',
        },
        {
          linkId: 'north-coast:culture-north:star-maps',
          regionId: 'north-coast',
          cultureId: 'culture-north',
          discoveryId: 'star-maps',
          eventIds: [],
          eventTitles: [],
          eventCount: 0,
          activeResearchCount: 1,
          label: 'star-maps · north-coast',
        },
        {
          linkId: 'north-coast:culture-north:tidal-ledgers',
          regionId: 'north-coast',
          cultureId: 'culture-north',
          discoveryId: 'tidal-ledgers',
          eventIds: [],
          eventTitles: [],
          eventCount: 0,
          activeResearchCount: 1,
          label: 'tidal-ledgers · north-coast',
        },
      ],
      unlockedResearchIds: ['astrolabe'],
      activeResearchCount: 1,
      eventIds: ['event-open-archives'],
      eventTitles: ['Open Archives'],
      eventCount: 1,
      eventPopups: [
        {
          popupId: 'north-coast:culture-north:event-open-archives:popup',
          eventId: 'event-open-archives',
          title: 'Open Archives',
          summary: 'Scholars share navigation routes.',
          triggeredAt: '2026-04-19T00:00:00.000Z',
          importance: 3,
          discoveries: ['public-catalogue'],
          unlockedResearchIds: ['astrolabe'],
          label: 'Open Archives · 2026-04-19',
          order: 1,
        },
      ],
      identityTags: ['assemblies', 'navigation', 'trade'],
      highlights: ['public-catalogue', 'star-maps', 'assemblies'],
      cultureMetrics: {
        openness: 72,
        cohesion: 61,
        researchDrive: 77,
      },
      zoneRank: 0,
      overlapCount: 1,
      zoneBand: 'core',
      dominantInRegion: true,
      competingCultureIds: [],
      zoneContour: {
        radius: 22,
        feather: 2,
        ringCount: 1,
      },
      style: {
        color: 'violet',
        icon: '✦',
        emphasis: 'high',
        accent: 'iris',
        labelTone: 'visionary',
      },
      zoneStyle: {
        fill: 'violet',
        outline: 'violet',
        accent: 'iris',
        markerIcon: '✦',
        emphasis: 'high',
        labelTone: 'visionary',
        opacity: 0.7,
        pattern: 'radiant',
        surface: 'gloss',
        glow: 'luminous',
        blendMode: 'source-over',
        strokeWidth: 4,
      },
    },
  ]);
});

test('buildCultureMapOverlay distinguishes overlapping cultural influences in the same region', () => {
  const overlay = buildCultureMapOverlay(
    {
      cultures: [
        {
          id: 'culture-north',
          name: 'Northern League',
          archetype: 'maritime',
          primaryLanguage: 'north-tongue',
          valueIds: ['trade', 'navigation'],
          traditionIds: ['assemblies'],
          openness: 72,
          cohesion: 61,
          researchDrive: 77,
        },
        {
          id: 'culture-delta',
          name: 'Delta Scribes',
          archetype: 'scholarly',
          primaryLanguage: 'delta-script',
          valueIds: ['memory'],
          traditionIds: ['archives'],
          openness: 58,
          cohesion: 52,
          researchDrive: 64,
        },
      ],
      researchStates: [
        {
          id: 'research-astrolabe',
          cultureId: 'culture-north',
          topicId: 'astrolabe',
          status: 'active',
          progress: 65,
          discoveredConceptIds: ['star-maps', 'tidal-ledgers'],
        },
        {
          id: 'research-ledgers',
          cultureId: 'culture-delta',
          topicId: 'delta-ledgers',
          status: 'active',
          progress: 52,
          discoveredConceptIds: ['ink-network'],
        },
      ],
      historicalEvents: [],
    },
    {
      regionIdsByCulture: {
        'culture-north': ['shared-bay'],
        'culture-delta': ['shared-bay'],
      },
    },
  );

  assert.deepEqual(overlay, [
    {
      overlayId: 'shared-bay:culture-delta',
      regionId: 'shared-bay',
      cultureId: 'culture-delta',
      cultureName: 'Delta Scribes',
      archetype: 'scholarly',
      primaryLanguage: 'delta-script',
      markerType: 'balanced',
      influenceScore: 52,
      influenceTier: 'emerging',
      label: 'Delta Scribes (1 découvertes)',
      summary: '1 recherches actives, 0 événements, 2 repères culturels',
      discoveries: ['ink-network'],
      regionalDiscoveryLinks: [
        {
          linkId: 'shared-bay:culture-delta:ink-network',
          regionId: 'shared-bay',
          cultureId: 'culture-delta',
          discoveryId: 'ink-network',
          eventIds: [],
          eventTitles: [],
          eventCount: 0,
          activeResearchCount: 1,
          label: 'ink-network · shared-bay',
        },
      ],
      unlockedResearchIds: ['delta-ledgers'],
      activeResearchCount: 1,
      eventIds: [],
      eventTitles: [],
      eventCount: 0,
      eventPopups: [],
      identityTags: ['archives', 'memory'],
      highlights: ['ink-network', 'archives', 'memory'],
      cultureMetrics: {
        openness: 58,
        cohesion: 52,
        researchDrive: 64,
      },
      zoneRank: 1,
      overlapCount: 2,
      zoneBand: 'outer',
      dominantInRegion: false,
      competingCultureIds: ['culture-north'],
      zoneContour: {
        radius: 15,
        feather: 4,
        ringCount: 2,
      },
      style: {
        color: 'teal',
        icon: '◆',
        emphasis: 'normal',
        accent: 'seafoam',
        labelTone: 'measured',
      },
      zoneStyle: {
        fill: 'teal',
        outline: 'teal',
        accent: 'seafoam',
        markerIcon: '◆',
        emphasis: 'normal',
        labelTone: 'measured',
        opacity: 0.55,
        pattern: 'solid',
        surface: 'matte',
        glow: 'soft',
        blendMode: 'multiply',
        strokeWidth: 2,
      },
    },
    {
      overlayId: 'shared-bay:culture-north',
      regionId: 'shared-bay',
      cultureId: 'culture-north',
      cultureName: 'Northern League',
      archetype: 'maritime',
      primaryLanguage: 'north-tongue',
      markerType: 'innovation',
      influenceScore: 68,
      influenceTier: 'strong',
      label: 'Northern League (2 découvertes)',
      summary: '1 recherches actives, 0 événements, 3 repères culturels',
      discoveries: ['star-maps', 'tidal-ledgers'],
      regionalDiscoveryLinks: [
        {
          linkId: 'shared-bay:culture-north:star-maps',
          regionId: 'shared-bay',
          cultureId: 'culture-north',
          discoveryId: 'star-maps',
          eventIds: [],
          eventTitles: [],
          eventCount: 0,
          activeResearchCount: 1,
          label: 'star-maps · shared-bay',
        },
        {
          linkId: 'shared-bay:culture-north:tidal-ledgers',
          regionId: 'shared-bay',
          cultureId: 'culture-north',
          discoveryId: 'tidal-ledgers',
          eventIds: [],
          eventTitles: [],
          eventCount: 0,
          activeResearchCount: 1,
          label: 'tidal-ledgers · shared-bay',
        },
      ],
      unlockedResearchIds: ['astrolabe'],
      activeResearchCount: 1,
      eventIds: [],
      eventTitles: [],
      eventCount: 0,
      eventPopups: [],
      identityTags: ['assemblies', 'navigation', 'trade'],
      highlights: ['star-maps', 'tidal-ledgers', 'assemblies'],
      cultureMetrics: {
        openness: 72,
        cohesion: 61,
        researchDrive: 77,
      },
      zoneRank: 0,
      overlapCount: 2,
      zoneBand: 'core',
      dominantInRegion: true,
      competingCultureIds: ['culture-delta'],
      zoneContour: {
        radius: 22,
        feather: 4,
        ringCount: 2,
      },
      style: {
        color: 'violet',
        icon: '✦',
        emphasis: 'high',
        accent: 'iris',
        labelTone: 'visionary',
      },
      zoneStyle: {
        fill: 'violet',
        outline: 'violet',
        accent: 'iris',
        markerIcon: '✦',
        emphasis: 'high',
        labelTone: 'visionary',
        opacity: 0.7,
        pattern: 'radiant',
        surface: 'gloss',
        glow: 'luminous',
        blendMode: 'source-over',
        strokeWidth: 4,
      },
    },
  ]);
});

test('buildCultureMapOverlay supports plain payloads and style overrides', () => {
  const overlay = buildCultureMapOverlay(
    {
      cultures: [
        {
          id: 'culture-fractured',
          name: 'Broken Courts',
          archetype: 'courtly',
          primaryLanguage: 'court-speech',
          valueIds: ['prestige'],
          traditionIds: ['duels'],
          openness: 50,
          cohesion: 24,
          researchDrive: 58,
        },
      ],
      researchStates: [],
      historicalEvents: [],
    },
    {
      regionIdsByCulture: { 'culture-fractured': ['capital-basin'] },
      styleByMarkerType: {
        fragmented: { color: 'ruby', icon: '⚑', emphasis: 'critical' },
      },
    },
  );

  assert.deepEqual(overlay[0].style, {
    color: 'ruby',
    icon: '⚑',
    emphasis: 'critical',
    accent: 'ember',
    labelTone: 'volatile',
  });
  assert.equal(overlay[0].markerType, 'fragmented');
  assert.equal(overlay[0].influenceTier, 'faint');
  assert.equal(overlay[0].zoneStyle.pattern, 'fractured');
  assert.equal(overlay[0].zoneStyle.surface, 'shattered');
  assert.equal(overlay[0].zoneStyle.glow, 'sparking');
});

test('buildCultureMapOverlay can summarize overlapping culture clusters with discovery and event pins', () => {
  const overlay = buildCultureMapOverlay(
    {
      cultures: [
        {
          id: 'culture-harbor',
          name: 'Harbor Compact',
          archetype: 'maritime',
          primaryLanguage: 'harbor-cant',
          valueIds: ['trade'],
          traditionIds: ['pilots'],
          openness: 70,
          cohesion: 62,
          researchDrive: 76,
        },
        {
          id: 'culture-delta',
          name: 'Delta Scribes',
          archetype: 'scholarly',
          primaryLanguage: 'delta-script',
          valueIds: ['archives'],
          traditionIds: ['flood-books'],
          openness: 64,
          cohesion: 58,
          researchDrive: 72,
        },
      ],
      researchStates: [
        {
          id: 'research-harbor',
          cultureId: 'culture-harbor',
          topicId: 'tidal-ledgers',
          status: 'active',
          progress: 50,
          discoveredConceptIds: ['tidal-ledgers'],
        },
        {
          id: 'research-delta',
          cultureId: 'culture-delta',
          topicId: 'flood-archives',
          status: 'completed',
          progress: 100,
          completedAt: '2026-04-19T00:00:00.000Z',
          discoveredConceptIds: ['flood-archives'],
        },
      ],
      historicalEvents: [
        {
          id: 'event-harbor-forum',
          title: 'Harbor Forum',
          category: 'knowledge',
          summary: 'Pilots compare flood archive routes.',
          era: 'map-play',
          importance: 4,
          triggeredAt: '2026-04-20T00:00:00.000Z',
          affectedCultureIds: ['culture-harbor'],
          discoveryIds: ['tidal-ledgers'],
        },
      ],
    },
    {
      clusterSummaries: true,
      regionIdsByCulture: {
        'culture-harbor': ['shared-bay'],
        'culture-delta': ['shared-bay'],
      },
    },
  );

  assert.equal(overlay.length, 2);
  assert.deepEqual(overlay.map((entry) => entry.clusterSummary?.label), [
    '2 cultures · 2 découvertes',
    '2 cultures · 2 découvertes',
  ]);
  assert.deepEqual(overlay[0].clusterSummary, {
    clusterId: 'shared-bay:culture-cluster',
    regionId: 'shared-bay',
    cultureIds: ['culture-delta', 'culture-harbor'],
    cultureNames: ['Delta Scribes', 'Harbor Compact'],
    cultureCount: 2,
    discoveryIds: ['flood-archives', 'tidal-ledgers'],
    discoveryCount: 2,
    eventCount: 1,
    pins: [
      {
        pinId: 'shared-bay:culture-harbor:event:event-harbor-forum',
        kind: 'event',
        name: 'Harbor Forum',
        type: 'knowledge',
        regionId: 'shared-bay',
        cultureId: 'culture-harbor',
        cultureName: 'Harbor Compact',
        importance: 4,
      },
      {
        pinId: 'shared-bay:culture-delta:discovery:flood-archives',
        kind: 'discovery',
        name: 'flood-archives',
        type: 'Découverte',
        regionId: 'shared-bay',
        cultureId: 'culture-delta',
        cultureName: 'Delta Scribes',
        importance: null,
      },
      {
        pinId: 'shared-bay:culture-harbor:discovery:tidal-ledgers',
        kind: 'discovery',
        name: 'tidal-ledgers',
        type: 'Découverte',
        regionId: 'shared-bay',
        cultureId: 'culture-harbor',
        cultureName: 'Harbor Compact',
        importance: null,
      },
    ],
    label: '2 cultures · 2 découvertes',
    summary: 'Delta Scribes, Harbor Compact',
  });
});

test('buildCultureMapOverlay rejects invalid inputs', () => {
  assert.throws(() => buildCultureMapOverlay(null), /payload must be an object/);
  assert.throws(
    () => buildCultureMapOverlay({ cultures: null, researchStates: [], historicalEvents: [] }),
    /payload\.cultures must be an array/,
  );
  assert.throws(
    () => buildCultureMapOverlay({ cultures: [null], researchStates: [], historicalEvents: [] }),
    /Culture instances or plain objects/,
  );
  assert.throws(
    () => buildCultureMapOverlay({ cultures: [], researchStates: [null], historicalEvents: [] }),
    /ResearchState instances or plain objects/,
  );
  assert.throws(
    () => buildCultureMapOverlay({ cultures: [], researchStates: [], historicalEvents: [] }, { regionIdsByCulture: [] }),
    /regionIdsByCulture must be an object/,
  );
});
