import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const webAppSource = readFileSync(new URL('../../../web/app.js', import.meta.url), 'utf8');
const stylesSource = readFileSync(new URL('../../../web/styles.css', import.meta.url), 'utf8');

test('culture urgency badges render compact local timeline reasons', () => {
  assert.match(webAppSource, /hint\.urgency\?\.reason/);
  assert.match(webAppSource, /culture-opportunity-reminder__reason/);
  assert.match(webAppSource, /reminder\.reasonCopy/);
  assert.match(webAppSource, /aria-label="Voir \$\{reminder\.focusCopy\}: \$\{reminder\.urgency\?\.detail/);
  assert.match(webAppSource, /culture-opportunity-reminder__action/);
  assert.match(webAppSource, /reminder\.recommendedAction\?\.summary/);
  assert.match(webAppSource, /culture-opportunity-reminder__tradeoff/);
  assert.match(webAppSource, /reminder\.tradeoff\?\.summary/);
  assert.match(webAppSource, /culture-opportunity-reminder__ripples/);
  assert.match(webAppSource, /reminder\.rippleEffects/);
  assert.match(webAppSource, /culture-opportunity-reminder__confidence/);
  assert.match(webAppSource, /reminder\.confidenceCue\?\.summary/);
  assert.match(webAppSource, /culture-opportunity-reminder__inaction/);
  assert.match(webAppSource, /reminder\.inactionCost\?\.summary/);
  assert.match(webAppSource, /culture-opportunity-priority-conflicts/);
  assert.match(webAppSource, /report\.priorityConflicts/);
  assert.match(webAppSource, /Conflits de priorité culturelle/);
  assert.match(webAppSource, /culture-opportunity-reminder__stability-preview/);
  assert.match(webAppSource, /reminder\.stabilityPreview/);
  assert.match(webAppSource, /Aperçu de stabilité culturelle/);
  assert.match(webAppSource, /culture-opportunity-reminder__queue-action/);
  assert.match(webAppSource, /data-culture-queue-action/);
  assert.match(webAppSource, /culture-opportunity-queued-action/);
  assert.match(webAppSource, /culture-opportunity-reminder__queue-confirmation/);
  assert.match(webAppSource, /data-culture-undo-action/);
  assert.match(webAppSource, /queuedCultureActions/);
  assert.match(webAppSource, /cultureQueueAction/);
  assert.match(webAppSource, /cultureUndoAction/);
  assert.match(webAppSource, /Action culturelle en file/);
  assert.match(webAppSource, /culture-opportunity-resolution/);
  assert.match(webAppSource, /Résumé de résolution culturelle/);
  assert.match(webAppSource, /Urgences non couvertes/);
  assert.match(webAppSource, /cultureTensionMarkers/);
  assert.match(webAppSource, /buildPostCommitCultureTensionMarkers/);
  assert.match(webAppSource, /culture-tension-marker/);
  assert.match(webAppSource, /Tensions culturelles après résolution/);
  assert.match(webAppSource, /cultureTensionFilters/);
  assert.match(webAppSource, /data-culture-tension-filter/);
  assert.match(webAppSource, /data-culture-tension-jump/);
  assert.match(webAppSource, /Accès rapide aux tensions culturelles prioritaires/);
  assert.match(webAppSource, /Mettre en file/);
  assert.match(webAppSource, /Aucune action culturelle pertinente/);
  assert.match(webAppSource, /Pas de perte culturelle claire/);
  assert.match(webAppSource, /Aucun effet de propagation culturel en file/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__reason/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__action/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__tradeoff/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__confidence--high/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__confidence--mixed/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__confidence--risky/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__inaction--closing/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__inaction--low/);
  assert.match(stylesSource, /\.culture-opportunity-priority-conflict--urgent/);
  assert.match(stylesSource, /\.culture-opportunity-priority-conflict--shared/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__stability-preview--urgent/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__stability-preview--steady/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__queue-action/);
  assert.match(stylesSource, /\.culture-opportunity-queued-action/);
  assert.match(stylesSource, /\.culture-opportunity-resolution/);
  assert.match(stylesSource, /\.culture-opportunity-resolution__uncovered/);
  assert.match(stylesSource, /\.culture-tension-marker/);
  assert.match(stylesSource, /\.culture-tension-marker-card--escalated/);
  assert.match(stylesSource, /\.culture-tension-filters/);
  assert.match(stylesSource, /\.culture-tension-quick-jump/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__queue-confirmation/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__queue-empty/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__ripple--positive/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__ripple--uncertain/);
  assert.match(stylesSource, /\.culture-opportunity-reminder__ripple--risky/);
});
