import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const webAppSource = readFileSync(new URL('../../../web/app.js', import.meta.url), 'utf8');
const stylesSource = readFileSync(new URL('../../../web/styles.css', import.meta.url), 'utf8');

test('world map atlas renders culture influence zones from existing culture overlay data', () => {
  assert.match(webAppSource, /function buildAtlasCultureFeatures/);
  assert.match(webAppSource, /cultureView\?\.overlay/);
  assert.match(webAppSource, /getProvincePolygon\(entry\.regionId\)/);
  assert.match(webAppSource, /getProvinceCenter\(entry\.regionId\)/);
  assert.match(webAppSource, /atlas-culture-zone--\$\{zone\.tone\}/);
  assert.match(webAppSource, /renderAtlasWorldCanvas\(shell, economyView, cultureView\)/);
  assert.match(webAppSource, /regionSummaries/);
  assert.match(webAppSource, /atlas-culture-summary/);
  assert.match(webAppSource, /influence contestée/);
  assert.match(webAppSource, /opportunité:/);
  assert.match(webAppSource, /function buildAtlasCultureDrift/);
  assert.match(webAppSource, /driftPreviews/);
  assert.match(webAppSource, /atlas-culture-drift--\$\{summary\.drift\.state\}/);
  assert.match(webAppSource, /borderZones/);
  assert.match(webAppSource, /atlas-cultural-border-zones/);
  assert.match(webAppSource, /Frontières instables|Médiations culturelles/);
  assert.match(webAppSource, /function buildAtlasCultureMediation/);
  assert.match(webAppSource, /zone\.mediation\.option/);
  assert.match(webAppSource, /zone\.mediation\.confidence/);
  assert.match(webAppSource, /zone\.mediation\.consequences\.appeasement/);
  assert.match(webAppSource, /function buildAtlasMediationCommitment/);
  assert.match(webAppSource, /zone\.commitment\.nextConsequence/);
  assert.match(webAppSource, /function buildAtlasMediationSignalWarnings/);
  assert.match(webAppSource, /renderCultureMediationSignalWarnings/);
  assert.match(webAppSource, /outcomeStatus/);
  assert.match(webAppSource, /atlas-mediation-outcome/);
  assert.match(webAppSource, /reboundWindow/);
  assert.match(webAppSource, /atlas-cultural-rebound-window/);
  assert.match(webAppSource, /consolidation/);
  assert.match(webAppSource, /buildAtlasFragileReboundRecommendation/);
  assert.match(webAppSource, /consolidationRecommendations/);
  assert.match(webAppSource, /buildAtlasConsolidationFollowUpStatus/);
  assert.match(webAppSource, /buildAtlasStaleRiskFallbackMove/);
  assert.match(webAppSource, /buildAtlasLatestSafeFallbackTurn/);
  assert.match(webAppSource, /buildAtlasPairedMediationSupport/);
  assert.match(webAppSource, /buildAtlasSafestPairedSupport/);
  assert.match(webAppSource, /buildAtlasPairedSupportSafetyJustification/);
  assert.match(webAppSource, /buildAtlasPairedSupportRiskRelief/);
});

test('world map atlas exposes discovery sites without adding a new culture source of truth', () => {
  assert.match(webAppSource, /regionalDiscoveryLinks\.slice\(0, densityMode === 'dense' \? 1 : 2\)/);
  assert.match(webAppSource, /atlas-discovery-site/);
  assert.match(webAppSource, /data-atlas-discovery="\$\{site\.discoveryId\}"/);
  assert.match(webAppSource, /Couche atlas culture et découvertes/);
  assert.match(webAppSource, /focused: entry\.regionId === selectedRegionId/);
  assert.match(webAppSource, /is-focused/);
  assert.match(webAppSource, /is-related/);
  assert.match(webAppSource, /atlas-discovery-site__link/);
  assert.match(webAppSource, /const discoveryClusters =/);
  assert.match(webAppSource, /const visibleDiscoverySites = discoverySites/);
  assert.match(webAppSource, /function offsetAtlasCulturePoint/);
  assert.match(webAppSource, /visualDensity: densityMode/);
  assert.match(webAppSource, /atlas-culture-layer--\$\{features\.visualDensity\}/);
  assert.match(webAppSource, /data-atlas-discovery-cluster="\$\{cluster\.regionId\}"/);
  assert.match(webAppSource, /D×\$\{cluster\.discoveryCount\}/);
  assert.match(webAppSource, /Cluster découvertes/);
  assert.match(webAppSource, /discoveryClusters,/);
  assert.match(webAppSource, /opportunityMarkers/);
  assert.match(webAppSource, /tensionMarkers/);
  assert.match(webAppSource, /atlas-culture-category-marker--opportunity/);
  assert.match(webAppSource, /atlas-culture-category-marker--tension/);
  assert.match(webAppSource, /linkedToFocus/);
  assert.match(webAppSource, /summary\.drift\.causes\.join/);
  assert.match(webAppSource, /mainDriver === 'migration'/);
  assert.match(webAppSource, /protéger découverte/);
  assert.match(webAppSource, /arbitrer influence/);
  assert.match(webAppSource, /pacte de frontière/);
  assert.match(webAppSource, /reboundWindow\.label/);
  assert.match(webAppSource, /aucun engagement · frontières stables/);
  assert.match(webAppSource, /confiance \$\{zone\.mediation\.confidence\}/);
  assert.match(webAppSource, /engagement stable/);
  assert.match(webAppSource, /engagement à risque/);
  assert.match(webAppSource, /reste \$\{zone\.commitment\.remainingConfidence\}/);
  assert.match(webAppSource, /sûre/);
  assert.match(webAppSource, /incertaine/);
  assert.match(webAppSource, /inconnue/);
  assert.match(webAppSource, /coût politique/);
  assert.match(webAppSource, /engagement trop optimiste/);
  assert.match(webAppSource, /médiation hors culture locale/);
  assert.match(webAppSource, /engagement cohérent/);
  assert.match(webAppSource, /réviser engagement/);
  assert.match(webAppSource, /renforcer suivi/);
  assert.match(webAppSource, /conserver médiation/);
  assert.match(webAppSource, /stabilisation possible/);
  assert.match(webAppSource, /rechute probable/);
  assert.match(webAppSource, /fenêtre manquée/);
  assert.match(webAppSource, /aucune fenêtre active/);
  assert.match(webAppSource, /rebond stable/);
  assert.match(webAppSource, /rebond fragile/);
  assert.match(webAppSource, /rebond expire/);
  assert.match(webAppSource, /engagement incomplet/);
  assert.match(webAppSource, /influence adverse/);
  assert.match(webAppSource, /délai restant faible/);
  assert.match(webAppSource, /reinforce mediation/);
  assert.match(webAppSource, /monitor drift/);
  assert.match(webAppSource, /protect border zone/);
  assert.match(webAppSource, /delay expansion/);
  assert.match(webAppSource, /Actions consolidation/);
  assert.match(webAppSource, /data-atlas-consolidation-action/);
  assert.match(webAppSource, /pending/);
  assert.match(webAppSource, /covered/);
  assert.match(webAppSource, /stale-risk/);
  assert.match(webAppSource, /closing window/);
  assert.match(webAppSource, /unresolved border pressure/);
  assert.match(webAppSource, /mediation drift/);
  assert.match(webAppSource, /atlas-cultural-border-zone__followup/);
  assert.match(webAppSource, /closing-window/);
  assert.match(webAppSource, /border-pressure/);
  assert.match(webAppSource, /const fallback = buildAtlasStaleRiskFallbackMove/);
  assert.match(webAppSource, /followUp\?\.state !== 'stale-risk'/);
  assert.match(webAppSource, /atlas-cultural-border-zone__fallback/);
  assert.match(webAppSource, /const latestSafeTurn = buildAtlasLatestSafeFallbackTurn/);
  assert.match(webAppSource, /followUp\?\.state !== 'stale-risk' \|\| !fallback/);
  assert.match(webAppSource, /state: 'immediate'/);
  assert.match(webAppSource, /state: 'one-turn-left'/);
  assert.match(webAppSource, /state: 'multi-turn'/);
  assert.match(webAppSource, /state: 'no-safe-window'/);
  assert.match(webAppSource, /dernier sûr:/);
  assert.match(webAppSource, /atlas-cultural-border-zone__latest-safe/);
  assert.match(webAppSource, /const pairedMediation = buildAtlasPairedMediationSupport/);
  assert.match(webAppSource, /state: 'needs-mediation'/);
  assert.match(webAppSource, /state: 'needs-border-pressure-relief'/);
  assert.match(webAppSource, /latestSafeTurn\?\.state === 'no-safe-window'/);
  assert.match(webAppSource, /fallback\.state === 'border-pressure' && commitment\.remainingConfidence === 'faible'/);
  assert.match(webAppSource, /atlas-cultural-border-zone__paired-mediation/);
  assert.match(webAppSource, /support:/);
  assert.match(webAppSource, /const safestSupport = buildAtlasSafestPairedSupport/);
  assert.match(webAppSource, /state: 'assign-mediator'/);
  assert.match(webAppSource, /state: 'ease-border-pressure'/);
  assert.match(webAppSource, /state: 'delay-until-safe-window'/);
  assert.match(webAppSource, /state: 'reinforce-local-trust'/);
  assert.match(webAppSource, /state: 'no-safe-pairing'/);
  assert.match(webAppSource, /!fallback \|\| !pairedMediation/);
  assert.match(webAppSource, /appui sûr:/);
  assert.match(webAppSource, /atlas-cultural-border-zone__safest-support/);
  assert.match(webAppSource, /const safetyJustification = buildAtlasPairedSupportSafetyJustification/);
  assert.match(webAppSource, /state: 'mediator-available'/);
  assert.match(webAppSource, /state: 'border-pressure-low'/);
  assert.match(webAppSource, /state: 'window-open'/);
  assert.match(webAppSource, /state: 'local-trust-sufficient'/);
  assert.match(webAppSource, /state: 'no-safe-justification'/);
  assert.match(webAppSource, /!fallback \|\| !pairedMediation \|\| !safestSupport/);
  assert.match(webAppSource, /safestSupport\.state === 'assign-mediator' && zone\.mediation\.confidence === 'inconnue'/);
  assert.match(webAppSource, /sûr car:/);
  assert.match(webAppSource, /atlas-cultural-border-zone__support-justification/);
  assert.match(webAppSource, /const riskRelief = buildAtlasPairedSupportRiskRelief/);
  assert.match(webAppSource, /riskRelief,/);
  assert.match(webAppSource, /state: 'mediation-stabilized'/);
  assert.match(webAppSource, /state: 'border-tension-calmed'/);
  assert.match(webAppSource, /state: 'window-preserved'/);
  assert.match(webAppSource, /state: 'local-trust-protected'/);
  assert.match(webAppSource, /safetyJustification\.state === 'no-safe-justification'/);
  assert.match(webAppSource, /risque retiré:/);
  assert.match(webAppSource, /atlas-cultural-border-zone__risk-relief/);
  assert.match(stylesSource, /\.atlas-culture-layer/);
  assert.match(stylesSource, /\.atlas-culture-zone--dominant/);
  assert.match(stylesSource, /\.atlas-discovery-site path/);
  assert.match(stylesSource, /\.atlas-culture-summary/);
  assert.match(stylesSource, /\.atlas-discovery-site\.is-focused path/);
  assert.match(stylesSource, /\.atlas-discovery-site__link/);
  assert.match(stylesSource, /\.atlas-discovery-cluster rect/);
  assert.match(stylesSource, /\.atlas-discovery-cluster\.is-selected rect/);
  assert.match(stylesSource, /\.atlas-culture-layer--dense/);
  assert.match(stylesSource, /\.atlas-culture-category-marker--opportunity/);
  assert.match(stylesSource, /\.atlas-culture-category-marker--tension/);
  assert.match(stylesSource, /@media \(max-width: 760px\)/);
  assert.match(stylesSource, /\.atlas-culture-summary__drift/);
  assert.match(stylesSource, /\.atlas-culture-drift--migre/);
  assert.match(stylesSource, /\.atlas-culture-drift\.is-linked-focus path/);
  assert.match(stylesSource, /\.atlas-cultural-border-zones/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone--migre/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__mediation/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__risk/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__recommendation/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__followup--stale-risk/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__fallback--closing-window/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__fallback--border-pressure/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__latest-safe--immediate/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__latest-safe--one-turn-left/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__latest-safe--multi-turn/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__latest-safe--no-safe-window/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__paired-mediation--needs-mediation/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__paired-mediation--needs-border-pressure-relief/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__safest-support--assign-mediator/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__safest-support--ease-border-pressure/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__safest-support--delay-until-safe-window/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__safest-support--reinforce-local-trust/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__safest-support--no-safe-pairing/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__support-justification--mediator-available/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__support-justification--border-pressure-low/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__support-justification--window-open/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__support-justification--local-trust-sufficient/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__support-justification--no-safe-justification/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__risk-relief--mediation-stabilized/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__risk-relief--window-preserved/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__risk-relief--border-tension-calmed/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__risk-relief--local-trust-protected/);
  assert.match(stylesSource, /\.atlas-cultural-border-zones\.is-stable rect/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__confidence/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__consequences/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone--confidence-incertaine/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__commitment/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone--commitment-risk/);
  assert.match(stylesSource, /\.culture-mediation-warnings/);
  assert.match(stylesSource, /\.culture-mediation-warning--conflict/);
  assert.match(stylesSource, /\.culture-mediation-warning--coherent/);
  assert.match(stylesSource, /\.atlas-mediation-outcome--améliore/);
  assert.match(stylesSource, /\.atlas-mediation-outcome--instable/);
  assert.match(stylesSource, /\.atlas-mediation-outcome--contredit/);
  assert.match(stylesSource, /\.atlas-cultural-rebound-window--favorable/);
  assert.match(stylesSource, /\.atlas-cultural-rebound-window--risky/);
  assert.match(stylesSource, /\.atlas-cultural-rebound-window--missed/);
  assert.match(stylesSource, /\.atlas-cultural-rebound-window--consolidation-stable/);
  assert.match(stylesSource, /\.atlas-cultural-rebound-window--consolidation-fragile/);
  assert.match(stylesSource, /\.atlas-cultural-rebound-window--consolidation-expiring/);
  assert.match(stylesSource, /\.atlas-cultural-consolidation-actions/);
  assert.match(stylesSource, /\.atlas-cultural-consolidation-action--fragile/);
  assert.match(stylesSource, /\.atlas-cultural-consolidation-action--followup-pending/);
  assert.match(stylesSource, /\.atlas-cultural-consolidation-action--followup-covered/);
  assert.match(stylesSource, /\.atlas-cultural-consolidation-action--followup-stale-risk/);
  assert.match(stylesSource, /\.atlas-cultural-consolidation-action__fallback/);
  assert.match(stylesSource, /\.atlas-cultural-consolidation-action__latest-safe/);
  assert.match(stylesSource, /\.atlas-cultural-consolidation-action__paired-mediation/);
  assert.match(stylesSource, /\.atlas-cultural-consolidation-action__safest-support/);
  assert.match(stylesSource, /\.atlas-cultural-consolidation-action__support-justification/);
  assert.match(stylesSource, /\.atlas-cultural-consolidation-action__risk-relief/);
});
