import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const webAppSource = readFileSync(new URL('../../../web/app.js', import.meta.url), 'utf8');
const stylesSource = readFileSync(new URL('../../../web/styles.css', import.meta.url), 'utf8');

test('world map atlas renders culture influence zones from existing culture overlay data', () => {
  assert.match(webAppSource, /function buildAtlasCultureFeatures/);
  assert.match(webAppSource, /cultureView\?\.overlay/);
  assert.match(webAppSource, /getProvincePolygon\(entry\.regionId\)/);
  assert.match(webAppSource, /getProvinceCenter\(entry\.regionId\)/);
  assert.match(webAppSource, /atlas-culture-zone--\$\{zone\.tone\}/);
  assert.match(webAppSource, /renderAtlasWorldCanvas\(shell, economyView, cultureView\)/);
  assert.match(webAppSource, /regionSummaries/);
  assert.match(webAppSource, /atlas-culture-summary/);
  assert.match(webAppSource, /influence contestée/);
  assert.match(webAppSource, /opportunité:/);
  assert.match(webAppSource, /function buildAtlasCultureDrift/);
  assert.match(webAppSource, /driftPreviews/);
  assert.match(webAppSource, /atlas-culture-drift--\$\{summary\.drift\.state\}/);
  assert.match(webAppSource, /borderZones/);
  assert.match(webAppSource, /atlas-cultural-border-zones/);
  assert.match(webAppSource, /Frontières instables|Médiations culturelles/);
  assert.match(webAppSource, /function buildAtlasCultureMediation/);
  assert.match(webAppSource, /zone\.mediation\.option/);
  assert.match(webAppSource, /zone\.mediation\.confidence/);
  assert.match(webAppSource, /zone\.mediation\.consequences\.appeasement/);
  assert.match(webAppSource, /function buildAtlasMediationCommitment/);
  assert.match(webAppSource, /zone\.commitment\.nextConsequence/);
  assert.match(webAppSource, /function buildAtlasMediationSignalWarnings/);
  assert.match(webAppSource, /renderCultureMediationSignalWarnings/);
  assert.match(webAppSource, /outcomeStatus/);
  assert.match(webAppSource, /atlas-mediation-outcome/);
  assert.match(webAppSource, /reboundWindow/);
  assert.match(webAppSource, /atlas-cultural-rebound-window/);
});

test('world map atlas exposes discovery sites without adding a new culture source of truth', () => {
  assert.match(webAppSource, /regionalDiscoveryLinks\.slice\(0, 2\)/);
  assert.match(webAppSource, /atlas-discovery-site/);
  assert.match(webAppSource, /data-atlas-discovery="\$\{site\.discoveryId\}"/);
  assert.match(webAppSource, /Couche atlas culture et découvertes/);
  assert.match(webAppSource, /focused: entry\.regionId === selectedRegionId/);
  assert.match(webAppSource, /is-focused/);
  assert.match(webAppSource, /is-related/);
  assert.match(webAppSource, /atlas-discovery-site__link/);
  assert.match(webAppSource, /linkedToFocus/);
  assert.match(webAppSource, /summary\.drift\.causes\.join/);
  assert.match(webAppSource, /mainDriver === 'migration'/);
  assert.match(webAppSource, /protéger découverte/);
  assert.match(webAppSource, /arbitrer influence/);
  assert.match(webAppSource, /pacte de frontière/);
  assert.match(webAppSource, /reboundWindow\.label/);
  assert.match(webAppSource, /aucun engagement · frontières stables/);
  assert.match(webAppSource, /confiance \$\{zone\.mediation\.confidence\}/);
  assert.match(webAppSource, /engagement stable/);
  assert.match(webAppSource, /engagement à risque/);
  assert.match(webAppSource, /reste \$\{zone\.commitment\.remainingConfidence\}/);
  assert.match(webAppSource, /sûre/);
  assert.match(webAppSource, /incertaine/);
  assert.match(webAppSource, /inconnue/);
  assert.match(webAppSource, /coût politique/);
  assert.match(webAppSource, /engagement trop optimiste/);
  assert.match(webAppSource, /médiation hors culture locale/);
  assert.match(webAppSource, /engagement cohérent/);
  assert.match(webAppSource, /réviser engagement/);
  assert.match(webAppSource, /renforcer suivi/);
  assert.match(webAppSource, /conserver médiation/);
  assert.match(webAppSource, /stabilisation possible/);
  assert.match(webAppSource, /rechute probable/);
  assert.match(webAppSource, /fenêtre manquée/);
  assert.match(webAppSource, /aucune fenêtre active/);
  assert.match(stylesSource, /\.atlas-culture-layer/);
  assert.match(stylesSource, /\.atlas-culture-zone--dominant/);
  assert.match(stylesSource, /\.atlas-discovery-site path/);
  assert.match(stylesSource, /\.atlas-culture-summary/);
  assert.match(stylesSource, /\.atlas-discovery-site\.is-focused path/);
  assert.match(stylesSource, /\.atlas-discovery-site__link/);
  assert.match(stylesSource, /\.atlas-culture-summary__drift/);
  assert.match(stylesSource, /\.atlas-culture-drift--migre/);
  assert.match(stylesSource, /\.atlas-culture-drift\.is-linked-focus path/);
  assert.match(stylesSource, /\.atlas-cultural-border-zones/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone--migre/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__mediation/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__risk/);
  assert.match(stylesSource, /\.atlas-cultural-border-zones\.is-stable rect/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__confidence/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__consequences/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone--confidence-incertaine/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone__commitment/);
  assert.match(stylesSource, /\.atlas-cultural-border-zone--commitment-risk/);
  assert.match(stylesSource, /\.culture-mediation-warnings/);
  assert.match(stylesSource, /\.culture-mediation-warning--conflict/);
  assert.match(stylesSource, /\.culture-mediation-warning--coherent/);
  assert.match(stylesSource, /\.atlas-mediation-outcome--améliore/);
  assert.match(stylesSource, /\.atlas-mediation-outcome--instable/);
  assert.match(stylesSource, /\.atlas-mediation-outcome--contredit/);
  assert.match(stylesSource, /\.atlas-cultural-rebound-window--favorable/);
  assert.match(stylesSource, /\.atlas-cultural-rebound-window--risky/);
  assert.match(stylesSource, /\.atlas-cultural-rebound-window--missed/);
});
