import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const webAppSource = readFileSync(new URL('../../../web/app.js', import.meta.url), 'utf8');
const stylesSource = readFileSync(new URL('../../../web/styles.css', import.meta.url), 'utf8');

test('playable province detail renders compact logistics route causes', () => {
  assert.match(webAppSource, /function renderProvinceLogisticsChoicePreview/);
  assert.match(webAppSource, /province-logistics-cause-summary/);
  assert.match(webAppSource, /Cause locale/);
  assert.match(webAppSource, /option\.causeLabel/);
  assert.match(webAppSource, /option\.cause/);
  assert.match(webAppSource, /province-logistics-recovery-comparison/);
  assert.match(webAppSource, /choice\.benefit/);
  assert.match(webAppSource, /choice\.blocker/);
  assert.match(webAppSource, /choice\.bottleneck/);
  assert.match(webAppSource, /Goulot/);
  assert.match(webAppSource, /choice\.rationale/);
  assert.match(webAppSource, /province-logistics-timeline-summary/);
  assert.match(webAppSource, /province-logistics-downstream-summary/);
  assert.match(webAppSource, /province-logistics-priority-summary/);
  assert.match(webAppSource, /Priorité aval/);
  assert.match(webAppSource, /preview\.priorityActions/);
  assert.match(webAppSource, /action\.tradeoff/);
  assert.match(webAppSource, /province-logistics-impact-preview/);
  assert.match(webAppSource, /Impact si engagé/);
  assert.match(webAppSource, /selectedActionPreview/);
  assert.match(webAppSource, /badge\.value/);
  assert.match(webAppSource, /province-logistics-queue-action/);
  assert.match(webAppSource, /Action carte/);
  assert.match(webAppSource, /Engager récupération/);
  assert.match(webAppSource, /data-logistics-queue-action/);
  assert.match(webAppSource, /queuedLogisticsActions/);
  assert.match(webAppSource, /primaryLogisticsAction/);
  assert.match(webAppSource, /renderQueuedLogisticsMapSummary/);
  assert.match(webAppSource, /buildLogisticsTurnCommitSummary/);
  assert.match(webAppSource, /renderLogisticsTurnCommitSummary/);
  assert.match(webAppSource, /buildLogisticsOutcomeMarkers/);
  assert.match(webAppSource, /renderProvinceLogisticsOutcomeMarker/);
  assert.match(webAppSource, /renderLogisticsOutcomeRouteBadge/);
  assert.match(webAppSource, /logisticsOutcomeMarkers/);
  assert.match(webAppSource, /data-logistics-outcome-marker/);
  assert.match(webAppSource, /Pénurie résolue/);
  assert.match(webAppSource, /Nouveau goulot/);
  assert.match(webAppSource, /Synthèse pénuries restantes/);
  assert.match(webAppSource, /File logistique/);
  assert.match(webAppSource, /Avant validation du tour/);
  assert.match(webAppSource, /unresolvedShortages/);
  assert.match(webAppSource, /redundantActions/);
  assert.match(webAppSource, /data-logistics-undo-last/);
  assert.match(webAppSource, /Annuler dernière action/);
  assert.match(webAppSource, /bottleneckRelieved/);
  assert.match(webAppSource, /downstreamEffect/);
  assert.match(webAppSource, /pénurie/);
  assert.match(webAppSource, /Pénuries aval/);
  assert.match(webAppSource, /choice\.downstreamShortages/);
  assert.match(webAppSource, /shortage\.detail/);
  assert.match(webAppSource, /Timeline récupération/);
  assert.match(webAppSource, /province-logistics-recovery-timeline/);
  assert.match(webAppSource, /choice\.timeline/);
  assert.match(webAppSource, /step\.detail/);
  assert.match(webAppSource, /step\.bottleneck/);
  assert.match(webAppSource, /province-logistics-neighbor-effects/);
  assert.match(webAppSource, /effect\.detail/);
  assert.match(webAppSource, /effect\.target/);
  assert.match(webAppSource, /logistique stable/);
  assert.equal(webAppSource.includes("if (preview.options.length === 0) {\n    return '';\n  }"), false);
  assert.match(stylesSource, /\.province-logistics-cause-summary/);
  assert.match(stylesSource, /province-logistics-cause-summary--high/);
  assert.match(stylesSource, /province-logistics-cause-summary--stable/);
  assert.match(stylesSource, /province-logistics-choice__cause/);
  assert.match(stylesSource, /province-logistics-recovery-comparison/);
  assert.match(stylesSource, /province-logistics-recovery--high/);
  assert.match(stylesSource, /province-logistics-recovery--medium/);
  assert.match(stylesSource, /province-logistics-bottleneck--high/);
  assert.match(stylesSource, /province-logistics-bottleneck--medium/);
  assert.match(stylesSource, /province-logistics-bottleneck--low/);
  assert.match(stylesSource, /province-logistics-timeline-summary--queued/);
  assert.match(stylesSource, /province-logistics-downstream-summary--aggravée/);
  assert.match(stylesSource, /province-logistics-priority-summary/);
  assert.match(stylesSource, /province-logistics-priority-list/);
  assert.match(stylesSource, /province-logistics-priority--high/);
  assert.match(stylesSource, /province-logistics-impact-preview--critical/);
  assert.match(stylesSource, /province-logistics-impact-badge--medium/);
  assert.match(stylesSource, /province-logistics-queue-action--ready/);
  assert.match(stylesSource, /province-logistics-queue-action--conflict/);
  assert.match(stylesSource, /province-logistics-queued-summary/);
  assert.match(stylesSource, /province-logistics-queued-summary--empty/);
  assert.match(stylesSource, /province-logistics-turn-summary--covered/);
  assert.match(stylesSource, /province-logistics-turn-summary--danger/);
  assert.match(stylesSource, /province-logistics-turn-summary__shortage--high/);
  assert.match(stylesSource, /province-node__logistics-outcome--resolved/);
  assert.match(stylesSource, /province-node__logistics-outcome--new-bottleneck/);
  assert.match(stylesSource, /economy-logistics-outcome--unresolved/);
  assert.match(stylesSource, /province-logistics-downstream-summary--résolue/);
  assert.match(stylesSource, /province-logistics-downstream-shortage--high/);
  assert.match(stylesSource, /province-logistics-timeline-summary--empty/);
  assert.match(stylesSource, /province-logistics-recovery-timeline__step--medium/);
  assert.match(stylesSource, /province-logistics-neighbor-effect--medium/);
  assert.match(stylesSource, /province-logistics-neighbor-effect--low/);
});
