import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const webAppSource = readFileSync(new URL('../../../web/app.js', import.meta.url), 'utf8');
const stylesSource = readFileSync(new URL('../../../web/styles.css', import.meta.url), 'utf8');

test('playable province detail renders compact logistics route causes', () => {
  assert.match(webAppSource, /function renderProvinceLogisticsChoicePreview/);
  assert.match(webAppSource, /buildProvinceLogisticsBottleneckWarnings/);
  assert.match(webAppSource, /buildProvinceLogisticsBottleneckPriorities/);
  assert.match(webAppSource, /buildProvinceLogisticsInterventionTradeoff/);
  assert.match(webAppSource, /buildProvinceLogisticsInterventionSequence/);
  assert.match(webAppSource, /buildProvinceLogisticsPressureComparison/);
  assert.match(webAppSource, /renderProvinceLogisticsPressureComparison/);
  assert.match(webAppSource, /province-logistics-bottleneck-warning/);
  assert.match(webAppSource, /province-logistics-bottleneck-priorities/);
  assert.match(webAppSource, /Priorités aval/);
  assert.match(webAppSource, /Raison du classement/);
  assert.match(webAppSource, /Action probable/);
  assert.match(webAppSource, /Compromis d’intervention logistique/);
  assert.match(webAppSource, /Séquence recommandée d’interventions logistiques/);
  assert.match(webAppSource, /Séquence recommandée/);
  assert.match(webAppSource, /Prévu vs résolu/);
  assert.match(webAppSource, /Comparaison pression logistique prévue et résolue/);
  assert.match(webAppSource, /Reste à traiter/);
  assert.match(webAppSource, /goulot amélioré/);
  assert.match(webAppSource, /pénurie persistante/);
  assert.match(webAppSource, /nouvelle contrainte aval/);
  assert.match(webAppSource, /alternative équivalente/);
  assert.match(webAppSource, /ordre dépendant du choix militaire/);
  assert.match(webAppSource, /ordre dépendant du choix culturel\/production/);
  assert.match(webAppSource, /interventionSequence/);
  assert.match(webAppSource, /Améliore/);
  assert.match(webAppSource, /Retarde/);
  assert.match(webAppSource, /Risque/);
  assert.match(webAppSource, /interventionTradeoff/);
  assert.match(webAppSource, /Renforce un autre goulot/);
  assert.match(webAppSource, /downstreamImpact/);
  assert.match(webAppSource, /recoveryAction/);
  assert.match(webAppSource, /Alerte goulot logistique/);
  assert.match(webAppSource, /Route logistique sous tension/);
  assert.match(webAppSource, /stock en tension haute/);
  assert.match(webAppSource, /sous tension autour de la province/);
  assert.match(webAppSource, /province-logistics-cause-summary/);
  assert.match(webAppSource, /Cause locale/);
  assert.match(webAppSource, /option\.causeLabel/);
  assert.match(webAppSource, /option\.cause/);
  assert.match(webAppSource, /province-logistics-recovery-comparison/);
  assert.match(webAppSource, /choice\.benefit/);
  assert.match(webAppSource, /choice\.blocker/);
  assert.match(webAppSource, /choice\.bottleneck/);
  assert.match(webAppSource, /Goulot/);
  assert.match(webAppSource, /choice\.rationale/);
  assert.match(webAppSource, /province-logistics-timeline-summary/);
  assert.match(webAppSource, /province-logistics-downstream-summary/);
  assert.match(webAppSource, /province-logistics-priority-summary/);
  assert.match(webAppSource, /Priorité aval/);
  assert.match(webAppSource, /preview\.priorityActions/);
  assert.match(webAppSource, /action\.tradeoff/);
  assert.match(webAppSource, /province-logistics-recovery-lever-ranking/);
  assert.match(webAppSource, /Leviers recovery/);
  assert.match(webAppSource, /preview\.recoveryLeverRanking/);
  assert.match(webAppSource, /lever\.primaryCost/);
  assert.match(webAppSource, /lever\.capacityCostDetail/);
  assert.match(webAppSource, /lever\.capacityComparison/);
  assert.match(webAppSource, /lever\.debtWatch/);
  assert.match(webAppSource, /Capacité:/);
  assert.match(webAppSource, /lever\.avoidedRisk/);
  assert.match(webAppSource, /lever\.mutualBlocker/);
  assert.match(webAppSource, /province-logistics-impact-preview/);
  assert.match(webAppSource, /Impact si engagé/);
  assert.match(webAppSource, /selectedActionPreview/);
  assert.match(webAppSource, /badge\.value/);
  assert.match(webAppSource, /province-logistics-secondary-bottleneck/);
  assert.match(webAppSource, /Goulot suivant/);
  assert.match(webAppSource, /secondaryBottleneckPreview/);
  assert.match(webAppSource, /Prochain goulot logistique après le levier recovery/);
  assert.match(webAppSource, /Suite recommandée/);
  assert.match(webAppSource, /nextRecommendation/);
  assert.match(webAppSource, /province-logistics-primary-secondary-tradeoff/);
  assert.match(webAppSource, /Compromis entre levier principal et bottleneck secondaire/);
  assert.match(webAppSource, /Secondaire prioritaire|Principal prioritaire/);
  assert.match(webAppSource, /primarySecondaryTradeoff/);
  assert.match(webAppSource, /province-logistics-secondary-relapse/);
  assert.match(webAppSource, /Risque après choix secondaire/);
  assert.match(webAppSource, /secondaryChoiceRelapsePreview/);
  assert.match(webAppSource, /Risque de rechute si le bottleneck secondaire est choisi/);
  assert.match(webAppSource, /province-logistics-capacity-conflict/);
  assert.match(webAppSource, /Conflit capacité/);
  assert.match(webAppSource, /Conflit de capacité entre récupération locale et route critique/);
  assert.match(webAppSource, /localRecoveryCapacityConflictWarning/);
  assert.match(webAppSource, /province-logistics-spillover-risk/);
  assert.match(webAppSource, /Spillover voisin/);
  assert.match(webAppSource, /Risque de spillover logistique sur routes voisines/);
  assert.match(webAppSource, /adjacentRouteSpilloverRisk/);
  assert.match(webAppSource, /Critique:/);
  assert.match(webAppSource, /Dépendance:/);
  assert.match(webAppSource, /dependencyTrace/);
  assert.match(webAppSource, /Garde:/);
  assert.match(webAppSource, /guardAction/);
  assert.match(webAppSource, /Comparaison garde:/);
  assert.match(webAppSource, /guardComparison/);
  assert.match(webAppSource, /Séquence:/);
  assert.match(webAppSource, /guardSequencing/);
  assert.match(webAppSource, /Coût opportunité:/);
  assert.match(webAppSource, /guardOpportunityCost/);
  assert.match(webAppSource, /province-logistics-spillover-stop/);
  assert.match(webAppSource, /stopMarker\.decisionLabel/);
  assert.match(webAppSource, /province-logistics-spillover-fallback/);
  assert.match(webAppSource, /fallbackAction\.label/);
  assert.match(webAppSource, /Repli:/);
  assert.match(webAppSource, /province-logistics-spillover-residual-benefit/);
  assert.match(webAppSource, /province-logistics-spillover-residual-risk/);
  assert.match(webAppSource, /Reste exposé:/);
  assert.match(webAppSource, /province-logistics-spillover-ladder/);
  assert.match(webAppSource, /guardDecisionSummary/);
  assert.match(webAppSource, /Synthèse garde:/);
  assert.match(webAppSource, /province-logistics-spillover-fallback-why/);
  assert.match(webAppSource, /fallbackJustification/);
  assert.match(webAppSource, /Pourquoi fallback:/);
  assert.match(webAppSource, /province-logistics-spillover-next-trigger/);
  assert.match(webAppSource, /nextChoiceTrigger/);
  assert.match(webAppSource, /Prochain déclencheur:/);
  assert.match(webAppSource, /Continuer la chaîne reste acceptable/);
  assert.match(webAppSource, /province-logistics-queue-action/);
  assert.match(webAppSource, /Action carte/);
  assert.match(webAppSource, /Engager récupération/);
  assert.match(webAppSource, /data-logistics-queue-action/);
  assert.match(webAppSource, /queuedLogisticsActions/);
  assert.match(webAppSource, /primaryLogisticsAction/);
  assert.match(webAppSource, /renderQueuedLogisticsMapSummary/);
  assert.match(webAppSource, /buildLogisticsTurnCommitSummary/);
  assert.match(webAppSource, /renderLogisticsTurnCommitSummary/);
  assert.match(webAppSource, /buildLogisticsOutcomeMarkers/);
  assert.match(webAppSource, /sortLogisticsOutcomeDetails/);
  assert.match(webAppSource, /getLogisticsOutcomeSeverityRank/);
  assert.match(webAppSource, /renderProvinceLogisticsOutcomeMarker/);
  assert.match(webAppSource, /renderLogisticsOutcomeRouteBadge/);
  assert.match(webAppSource, /renderFocusedLogisticsOutcomeGroup/);
  assert.match(webAppSource, /buildLogisticsRouteDecisionSummaries/);
  assert.match(webAppSource, /renderLogisticsOutcomeFilterControls/);
  assert.match(webAppSource, /renderLogisticsRouteDecisionList/);
  assert.match(webAppSource, /isLogisticsOutcomeVisible/);
  assert.match(webAppSource, /selectedLogisticsOutcomeRouteId/);
  assert.match(webAppSource, /data-logistics-route-summary/);
  assert.match(webAppSource, /is-logistics-outcome-highlighted/);
  assert.match(webAppSource, /is-logistics-outcome-dimmed/);
  assert.match(webAppSource, /logisticsOutcomeMarkers/);
  assert.match(webAppSource, /data-logistics-outcome-marker/);
  assert.match(webAppSource, /Pénurie résolue/);
  assert.match(webAppSource, /Nouveau goulot/);
  assert.match(webAppSource, /Synthèse pénuries restantes/);
  assert.match(webAppSource, /Résultat logistique groupé/);
  assert.match(webAppSource, /Résumé décisionnel des routes logistiques/);
  assert.match(webAppSource, /Routes visibles/);
  assert.match(webAppSource, /Routes masquées par filtre/);
  assert.match(webAppSource, /Action conseillée/);
  assert.match(webAppSource, /Route logistique sélectionnée depuis le résumé/);
  assert.match(webAppSource, /trié.*par gravité/);
  assert.match(webAppSource, /logistics-outcome-group:/);
  assert.match(webAppSource, /File logistique/);
  assert.match(webAppSource, /Avant validation du tour/);
  assert.match(webAppSource, /unresolvedShortages/);
  assert.match(webAppSource, /redundantActions/);
  assert.match(webAppSource, /data-logistics-undo-last/);
  assert.match(webAppSource, /Annuler dernière action/);
  assert.match(webAppSource, /bottleneckRelieved/);
  assert.match(webAppSource, /downstreamEffect/);
  assert.match(webAppSource, /pénurie/);
  assert.match(webAppSource, /Pénuries aval/);
  assert.match(webAppSource, /choice\.downstreamShortages/);
  assert.match(webAppSource, /shortage\.detail/);
  assert.match(webAppSource, /Timeline récupération/);
  assert.match(webAppSource, /province-logistics-recovery-timeline/);
  assert.match(webAppSource, /choice\.timeline/);
  assert.match(webAppSource, /step\.detail/);
  assert.match(webAppSource, /step\.bottleneck/);
  assert.match(webAppSource, /province-logistics-neighbor-effects/);
  assert.match(webAppSource, /effect\.detail/);
  assert.match(webAppSource, /effect\.target/);
  assert.match(webAppSource, /logistique stable/);
  assert.equal(webAppSource.includes("if (preview.options.length === 0) {\n    return '';\n  }"), false);
  assert.match(stylesSource, /\.province-logistics-cause-summary/);
  assert.match(stylesSource, /province-logistics-cause-summary--high/);
  assert.match(stylesSource, /province-logistics-cause-summary--stable/);
  assert.match(stylesSource, /province-logistics-choice__cause/);
  assert.match(stylesSource, /province-logistics-recovery-comparison/);
  assert.match(stylesSource, /province-logistics-recovery--high/);
  assert.match(stylesSource, /province-logistics-recovery--medium/);
  assert.match(stylesSource, /province-logistics-bottleneck--high/);
  assert.match(stylesSource, /province-logistics-bottleneck--medium/);
  assert.match(stylesSource, /province-logistics-bottleneck-warning--high/);
  assert.match(stylesSource, /province-logistics-bottleneck-warning--medium/);
  assert.match(stylesSource, /province-logistics-bottleneck-priorities/);
  assert.match(stylesSource, /province-logistics-bottleneck-tradeoff/);
  assert.match(stylesSource, /province-logistics-intervention-sequence/);
  assert.match(stylesSource, /province-logistics-pressure-comparison/);
  assert.match(stylesSource, /province-logistics-pressure-comparison__row--improved/);
  assert.match(stylesSource, /province-logistics-pressure-comparison__row--danger/);
  assert.match(stylesSource, /province-logistics-bottleneck-priority--high/);
  assert.match(stylesSource, /province-logistics-bottleneck-priority--medium/);
  assert.match(stylesSource, /province-logistics-bottleneck--low/);
  assert.match(stylesSource, /province-logistics-timeline-summary--queued/);
  assert.match(stylesSource, /province-logistics-downstream-summary--aggravée/);
  assert.match(stylesSource, /province-logistics-priority-summary/);
  assert.match(stylesSource, /province-logistics-priority-list/);
  assert.match(stylesSource, /province-logistics-priority--high/);
  assert.match(stylesSource, /province-logistics-impact-preview--critical/);
  assert.match(stylesSource, /province-logistics-impact-badge--medium/);
  assert.match(stylesSource, /province-logistics-queue-action--ready/);
  assert.match(stylesSource, /province-logistics-queue-action--conflict/);
  assert.match(stylesSource, /province-logistics-queued-summary/);
  assert.match(stylesSource, /province-logistics-queued-summary--empty/);
  assert.match(stylesSource, /province-logistics-turn-summary--covered/);
  assert.match(stylesSource, /province-logistics-turn-summary--danger/);
  assert.match(stylesSource, /province-logistics-turn-summary__shortage--high/);
  assert.match(stylesSource, /province-node__logistics-outcome--resolved/);
  assert.match(stylesSource, /province-node__logistics-outcome--new-bottleneck/);
  assert.match(stylesSource, /economy-logistics-outcome--unresolved/);
  assert.match(stylesSource, /province-logistics-outcome-group--unresolved/);
  assert.match(stylesSource, /province-logistics-outcome-group__item--new-bottleneck/);
  assert.match(stylesSource, /province-logistics-outcome-filter\.is-active/);
  assert.match(stylesSource, /province-logistics-route-decision--unresolved/);
  assert.match(stylesSource, /province-logistics-route-decisions__empty/);
  assert.match(stylesSource, /province-logistics-route-decision\.is-selected/);
  assert.match(stylesSource, /economy-route-group\.is-logistics-outcome-highlighted/);
  assert.match(stylesSource, /economy-route-group\.is-logistics-outcome-dimmed/);
  assert.match(stylesSource, /province-logistics-downstream-summary--résolue/);
  assert.match(stylesSource, /province-logistics-downstream-shortage--high/);
  assert.match(stylesSource, /province-logistics-timeline-summary--empty/);
  assert.match(stylesSource, /province-logistics-recovery-timeline__step--medium/);
  assert.match(stylesSource, /province-logistics-neighbor-effect--medium/);
  assert.match(stylesSource, /province-logistics-neighbor-effect--low/);
});
